-- ============================================================
-- CWC+ SUPABASE COMPLETE SETUP SCRIPT
-- Run this entire script in: Supabase > SQL Editor > New Query
-- ============================================================


-- ============================================================
-- STEP 1: TABLES
-- ============================================================

-- Recipes Table
CREATE TABLE IF NOT EXISTS recipes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  author      TEXT,
  time        TEXT,
  image       TEXT,
  category    TEXT,
  difficulty  TEXT,
  rating      NUMERIC(3,1) DEFAULT 4.5,
  base_servings INTEGER DEFAULT 2,
  ingredients JSONB DEFAULT '[]'::jsonb,
  steps       JSONB DEFAULT '[]'::jsonb,
  status      TEXT DEFAULT 'published',   -- 'published' | 'draft'
  is_featured BOOLEAN DEFAULT false,
  video       TEXT,
  tier_required TEXT DEFAULT 'Free',      -- 'Free' | 'Basic' | 'Plus' | 'Premium'
  volume      TEXT DEFAULT 'CWC Original',
  scheduled_post_date TIMESTAMP WITH TIME ZONE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Classes / Masterclasses Table
CREATE TABLE IF NOT EXISTS classes (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        TEXT NOT NULL,
  instructor   TEXT,
  duration     TEXT,
  price        TEXT DEFAULT '19.99',
  image        TEXT,
  video        TEXT,
  status       TEXT DEFAULT 'published',  -- 'published' | 'draft'
  tier_required TEXT DEFAULT 'Plus',
  is_featured  BOOLEAN DEFAULT false,
  ingredients  JSONB DEFAULT '[]'::jsonb,
  steps        JSONB DEFAULT '[]'::jsonb,
  notes        TEXT,
  attachments  JSONB DEFAULT '[]'::jsonb,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Force add columns for classes and recipes
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS ingredients JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS steps JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS attachments JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS ingredients JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS steps JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS live_link TEXT;
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;

-- People / Users Table (linked to Supabase Auth via auth.users.id)
CREATE TABLE IF NOT EXISTS people (
  id                UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name              TEXT,
  email             TEXT UNIQUE,
  subscription_tier TEXT DEFAULT 'Free',  -- 'Free' | 'Basic' | 'Plus' | 'Premium'
  role              TEXT DEFAULT 'user',
  unlocked_volumes  TEXT[] DEFAULT '{}',
  unlocked_classes  BIGINT[] DEFAULT '{}',
  avatar_url        TEXT,
  cover_url         TEXT,
  dietary_preferences TEXT[] DEFAULT '{}',
  favorite_food     TEXT,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Force add columns in case the table already existed before the upgrade
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS unlocked_volumes TEXT[] DEFAULT '{}';
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS unlocked_classes BIGINT[] DEFAULT '{}';
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS cover_url TEXT;
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS dietary_preferences TEXT[] DEFAULT '{}';
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS favorite_food TEXT;
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS push_subscription JSONB;

-- Merch Table
CREATE TABLE IF NOT EXISTS merch (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  price       NUMERIC(10,2),
  image       TEXT,
  category    TEXT,
  stock       INTEGER DEFAULT 0,
  status      TEXT DEFAULT 'published',
  scheduled_post_date TIMESTAMP WITH TIME ZONE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Platform Settings Table (Key-Value Store)
CREATE TABLE IF NOT EXISTS settings (
  id         TEXT PRIMARY KEY,
  config     JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id           TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  user_id      UUID REFERENCES auth.users(id),
  customer     TEXT,
  email        TEXT,
  phone        TEXT,
  address      TEXT,
  product      TEXT,
  amount       NUMERIC(10,2),
  status       TEXT DEFAULT 'pending',
  fulfillment  TEXT DEFAULT 'pending',
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID REFERENCES auth.users(id) ON DELETE CASCADE, -- NULL means global broadcast
  type            TEXT DEFAULT 'system', -- 'system', 'class', 'shop', 'alert', 'success'
  title           TEXT NOT NULL,
  message         TEXT NOT NULL,
  attachment_type TEXT, -- 'recipe', 'class', 'none'
  attachment_id   TEXT, -- ID or URL
  read_status     BOOLEAN DEFAULT false,
  scheduled_post_date TIMESTAMP WITH TIME ZONE,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ============================================================
-- STEP 2: AUTO-CREATE USER PROFILE ON GOOGLE SIGN-IN
-- This trigger fires whenever a new user signs up via
-- Google OAuth or Email — it auto-creates their 'people' row.
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.people (id, name, email, avatar_url, subscription_tier, role)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data ->> 'full_name',
      NEW.raw_user_meta_data ->> 'name',
      split_part(NEW.email, '@', 1)
    ),
    NEW.email,
    COALESCE(
      NEW.raw_user_meta_data ->> 'avatar_url',
      NEW.raw_user_meta_data ->> 'picture'
    ),
    'Free',
    CASE WHEN NEW.email = 'ononeline30@gmail.com' THEN 'admin' ELSE 'user' END
  )
  ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Attach trigger to auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- STEP 3: ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Enable RLS on all tables
ALTER TABLE recipes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE people   ENABLE ROW LEVEL SECURITY;
ALTER TABLE merch    ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Create is_team_member function
CREATE OR REPLACE FUNCTION public.is_team_member()
RETURNS BOOLEAN
LANGUAGE sql SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.people
    WHERE id = auth.uid() AND role IN ('admin', 'management', 'employee')
  );
$$;

-- ── RECIPES policies ─────────────────────────────────────────
-- Public can read published recipes
DROP POLICY IF EXISTS "Public can read published recipes" ON recipes;
CREATE POLICY "Public can read published recipes"
  ON recipes FOR SELECT
  USING (status = 'published');

-- Authenticated team members can do anything
DROP POLICY IF EXISTS "Admin full access to recipes" ON recipes;
CREATE POLICY "Admin full access to recipes"
  ON recipes FOR ALL
  USING (public.is_team_member());

-- ── CLASSES policies ─────────────────────────────────────────
DROP POLICY IF EXISTS "Public can read published classes" ON classes;
CREATE POLICY "Public can read published classes"
  ON classes FOR SELECT
  USING (status = 'published');

DROP POLICY IF EXISTS "Admin full access to classes" ON classes;
CREATE POLICY "Admin full access to classes"
  ON classes FOR ALL
  USING (public.is_team_member());

-- ── PEOPLE policies ──────────────────────────────────────────
-- Users can only read/update their own profile
DROP POLICY IF EXISTS "Users can view their own profile" ON people;
CREATE POLICY "Users can view their own profile"
  ON people FOR SELECT
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON people;
CREATE POLICY "Users can update their own profile"
  ON people FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Users can insert their own profile (needed for client-side upsert fallback)
DROP POLICY IF EXISTS "Users can insert their own profile" ON people;
CREATE POLICY "Users can insert their own profile"
  ON people FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Admin can view all users
DROP POLICY IF EXISTS "Admin can view all users" ON people;
CREATE POLICY "Admin can view all users"
  ON people FOR SELECT
  USING (public.is_team_member());

DROP POLICY IF EXISTS "Admin can update all users" ON people;
CREATE POLICY "Admin can update all users"
  ON people FOR UPDATE
  USING (public.is_team_member());

-- ── MERCH policies ───────────────────────────────────────────
DROP POLICY IF EXISTS "Public can read published merch" ON merch;
CREATE POLICY "Public can read published merch"
  ON merch FOR SELECT
  USING (status = 'published');

DROP POLICY IF EXISTS "Admin full access to merch" ON merch;
CREATE POLICY "Admin full access to merch"
  ON merch FOR ALL
  USING (public.is_team_member());

-- ── ORDERS policies ──────────────────────────────────────────
DROP POLICY IF EXISTS "Users can read their own orders" ON orders;
CREATE POLICY "Users can read their own orders"
  ON orders FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admin full access to orders" ON orders;
CREATE POLICY "Admin full access to orders"
  ON orders FOR ALL
  USING (public.is_team_member());

-- ── SETTINGS policies ────────────────────────────────────────
-- Settings are PUBLIC — currency, tiers, banner, site name must load for all visitors
DROP POLICY IF EXISTS "Authenticated can read settings" ON settings;
DROP POLICY IF EXISTS "Public can read settings" ON settings;
CREATE POLICY "Public can read settings"
  ON settings FOR SELECT
  USING (true);

-- Only admins can modify settings
DROP POLICY IF EXISTS "Admin full access to settings" ON settings;
CREATE POLICY "Admin full access to settings"
  ON settings FOR ALL
  USING (public.is_team_member());

-- ── NOTIFICATIONS policies ────────────────────────────────────────
-- Authenticated users can read their own notifications or global broadcasts
DROP POLICY IF EXISTS "Users can read their own or global notifications" ON notifications;
CREATE POLICY "Users can read their own or global notifications"
  ON notifications FOR SELECT
  USING (auth.uid() IS NOT NULL AND (auth.uid() = user_id OR user_id IS NULL));

-- Users can update their own notifications (e.g. mark as read)
DROP POLICY IF EXISTS "Users can update their own notifications" ON notifications;
CREATE POLICY "Users can update their own notifications"
  ON notifications FOR UPDATE
  USING (auth.uid() = user_id);

-- Admin can manage all notifications
DROP POLICY IF EXISTS "Admin full access to notifications" ON notifications;
CREATE POLICY "Admin full access to notifications"
  ON notifications FOR ALL
  USING (public.is_team_member());


-- ============================================================
-- STEP 4: DEFAULT PLATFORM SETTINGS
-- ============================================================

INSERT INTO settings (id, config) VALUES (
  'platform',
  '{
    "siteName": "CWC+",
    "heroTitle": "Unleash Your Inner Chef",
    "maintenanceMode": false,
    "bannerEnabled": true,
    "bannerText": "New Masterclass dropping this Friday! 🚀",
    "tierPrices": { "Basic": "5.99", "Plus": "10.99", "Premium": "35.99" },
    "plugins": { "stripe": true, "mailchimp": false, "zapier": true },
    "apiKeys": []
  }'::jsonb
) ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- STEP 5: SEED SAMPLE RECIPES (REMOVED - NO MOCK DATA)
-- ============================================================

-- ============================================================
-- STEP 6: SEED SAMPLE MASTERCLASSES (REMOVED - NO MOCK DATA)
-- ============================================================

-- ============================================================
-- STORAGE & NEW FIELDS FOR CLASS SCHEDULES
-- ============================================================
-- Create the storage bucket for public assets if it doesn't exist
INSERT INTO storage.buckets (id, name, public) 
VALUES ('public-assets', 'public-assets', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'public-assets');

DROP POLICY IF EXISTS "Allow Uploads" ON storage.objects;
CREATE POLICY "Allow Uploads" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'public-assets');

DROP POLICY IF EXISTS "Allow Updates" ON storage.objects;
CREATE POLICY "Allow Updates" 
ON storage.objects FOR UPDATE 
USING (bucket_id = 'public-assets');

DROP POLICY IF EXISTS "Allow Deletes" ON storage.objects;
CREATE POLICY "Allow Deletes" 
ON storage.objects FOR DELETE 
USING (bucket_id = 'public-assets');

-- Add new Date fields to classes
ALTER TABLE classes 
ADD COLUMN IF NOT EXISTS scheduled_post_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS live_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS notes TEXT;

-- Add new fields to recipes
ALTER TABLE recipes
ADD COLUMN IF NOT EXISTS video TEXT,
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS scheduled_post_date TIMESTAMP WITH TIME ZONE;

-- Add new fields to merch
ALTER TABLE merch
ADD COLUMN IF NOT EXISTS scheduled_post_date TIMESTAMP WITH TIME ZONE;

-- Add new fields to notifications
ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS scheduled_post_date TIMESTAMP WITH TIME ZONE;

-- Add new fields to people
ALTER TABLE people
ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';

-- Ensure god admin has the admin role (for existing accounts before the trigger was added)
UPDATE public.people 
SET role = 'admin' 
WHERE email = 'ononeline30@gmail.com';

-- ============================================================
-- DONE!
-- ============================================================
-- Next steps after running this script:
-- 1. Go to Supabase Dashboard > Authentication > Providers > Google
-- 2. Enable Google provider & enter your Google OAuth credentials
-- 3. Add redirect URL: https://your-project.supabase.co/auth/v1/callback
-- 4. In Authentication > URL Configuration, add:
--    - http://localhost:5173/auth/callback  (local dev)
--    - https://yourdomain.com/auth/callback (production)
-- ============================================================

-- ============================================================
-- STEP 7: MEDIA LIBRARY (CENTRALIZED ASSETS)
-- ============================================================

CREATE TABLE IF NOT EXISTS media_library (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename       TEXT NOT NULL,
  hero_url       TEXT NOT NULL,
  thumb_url      TEXT,
  card_url       TEXT,
  dominant_color TEXT,
  seo_schema     TEXT,
  type           TEXT DEFAULT 'image',
  created_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Alter existing tables to link to media
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS cover_image_id BIGINT REFERENCES media_library(id);
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS hero_image TEXT;
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS hero_image_id BIGINT REFERENCES media_library(id);

ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS thumbnail_image_id BIGINT REFERENCES media_library(id);
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS hero_image TEXT;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS hero_image_id BIGINT REFERENCES media_library(id);
ALTER TABLE public.merch ADD COLUMN IF NOT EXISTS media_id BIGINT REFERENCES media_library(id);

-- Support for generic files and metadata
ALTER TABLE public.media_library ADD COLUMN IF NOT EXISTS meta_data JSONB DEFAULT '{}'::jsonb;

ALTER TABLE media_library ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read media" ON media_library;
CREATE POLICY "Public can read media"
  ON media_library FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Admin full access to media" ON media_library;
CREATE POLICY "Admin full access to media"
  ON media_library FOR ALL
  USING (public.is_team_member());

-- --- PUSH NOTIFICATION AUTOMATION ---
-- This trigger automatically calls the Edge Function whenever a new notification is created

-- 1. Enable pg_net for HTTP requests
CREATE EXTENSION IF NOT EXISTS "pg_net";

-- 2. Trigger Function
CREATE OR REPLACE FUNCTION public.handle_broadcast_push()
RETURNS TRIGGER AS $$
BEGIN
  -- We call the edge function with the new record data
  PERFORM
    net.http_post(
      url := 'https://kkfctwmrgvrinoythhqb.supabase.co/functions/v1/send-push',
      headers := jsonb_build_object(
        'Content-Type', 'application/json'
      ),
      body := jsonb_build_object('record', row_to_json(NEW))
    );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. The Trigger
DROP TRIGGER IF EXISTS tr_send_push_on_broadcast ON public.notifications;
CREATE TRIGGER tr_send_push_on_broadcast
AFTER INSERT ON public.notifications
FOR EACH ROW EXECUTE FUNCTION public.handle_broadcast_push();


-- ============================================================
-- STEP 8: SECURITY HARDENING (run after initial setup)
-- ============================================================

-- ── Block role self-promotion ─────────────────────────────────
-- Helper: reads the caller's current role without triggering RLS recursion.
-- SECURITY DEFINER bypasses RLS on the subquery, preventing recursive policy evaluation.
CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS TEXT
LANGUAGE sql SECURITY DEFINER STABLE
AS $$
  SELECT role FROM public.people WHERE id = auth.uid();
$$;

DROP POLICY IF EXISTS "Users can update their own profile" ON people;
CREATE POLICY "Users can update their own profile"
  ON people FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (
    auth.uid() = id AND
    -- Prevent self-promotion: new role must match current role unless a team member is making the change
    (role = public.current_user_role() OR public.is_team_member())
  );

-- ── Add stripe_session_id, item_type, item_id to orders ──────
-- Allows verify-payment Edge Function to record what was purchased.
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS stripe_session_id TEXT,
  ADD COLUMN IF NOT EXISTS item_type         TEXT,
  ADD COLUMN IF NOT EXISTS item_id           TEXT;

-- Ensure orders.id has a UUID default (for existing tables created without it)
ALTER TABLE public.orders ALTER COLUMN id SET DEFAULT gen_random_uuid()::TEXT;

-- ── Secure content RPC: get_recipe_content ────────────────────
-- Replaces direct SELECT on ingredients/steps/notes/video.
-- Enforces tier access server-side before returning content.
CREATE OR REPLACE FUNCTION public.get_recipe_content(p_id BIGINT)
RETURNS TABLE(ingredients JSONB, steps JSONB, notes TEXT, video TEXT, tags JSONB)
LANGUAGE plpgsql SECURITY DEFINER
AS $$
DECLARE
  v_volume TEXT;
  v_tier   TEXT;
  v_unlocked_volumes TEXT[];
BEGIN
  SELECT volume INTO v_volume FROM public.recipes WHERE id = p_id AND status = 'published';
  IF NOT FOUND THEN RAISE EXCEPTION 'Recipe not found'; END IF;

  -- Free volume: open to all
  IF v_volume IS NULL OR v_volume = 'Free' THEN
    RETURN QUERY SELECT r.ingredients, r.steps, r.notes, r.video, r.tags
                 FROM public.recipes r WHERE r.id = p_id;
    RETURN;
  END IF;

  -- Unauthenticated: deny
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;

  -- Team members: full access
  IF public.is_team_member() THEN
    RETURN QUERY SELECT r.ingredients, r.steps, r.notes, r.video, r.tags
                 FROM public.recipes r WHERE r.id = p_id;
    RETURN;
  END IF;

  -- Check user's tier and individual unlocks
  SELECT subscription_tier, unlocked_volumes
    INTO v_tier, v_unlocked_volumes
    FROM public.people WHERE id = auth.uid();

  IF v_tier != 'Free' OR v_volume = ANY(v_unlocked_volumes) THEN
    RETURN QUERY SELECT r.ingredients, r.steps, r.notes, r.video, r.tags
                 FROM public.recipes r WHERE r.id = p_id;
  ELSE
    RAISE EXCEPTION 'Access denied: upgrade your membership to unlock this recipe';
  END IF;
END;
$$;

-- ── Secure content RPC: get_class_content ────────────────────
CREATE OR REPLACE FUNCTION public.get_class_content(p_id BIGINT)
RETURNS TABLE(video TEXT, ingredients JSONB, steps JSONB, notes TEXT, attachments JSONB, tags JSONB)
LANGUAGE plpgsql SECURITY DEFINER
AS $$
DECLARE
  v_tier_required  TEXT;
  v_user_tier      TEXT;
  v_unlocked_classes BIGINT[];
BEGIN
  SELECT tier_required INTO v_tier_required FROM public.classes WHERE id = p_id AND status = 'published';
  IF NOT FOUND THEN RAISE EXCEPTION 'Class not found'; END IF;

  -- Free tier: open to all
  IF v_tier_required IS NULL OR v_tier_required = 'Free' THEN
    RETURN QUERY SELECT c.video, c.ingredients, c.steps, c.notes, c.attachments, c.tags
                 FROM public.classes c WHERE c.id = p_id;
    RETURN;
  END IF;

  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Authentication required'; END IF;

  IF public.is_team_member() THEN
    RETURN QUERY SELECT c.video, c.ingredients, c.steps, c.notes, c.attachments, c.tags
                 FROM public.classes c WHERE c.id = p_id;
    RETURN;
  END IF;

  SELECT subscription_tier, unlocked_classes
    INTO v_user_tier, v_unlocked_classes
    FROM public.people WHERE id = auth.uid();

  IF v_user_tier != 'Free' OR p_id = ANY(v_unlocked_classes) THEN
    RETURN QUERY SELECT c.video, c.ingredients, c.steps, c.notes, c.attachments, c.tags
                 FROM public.classes c WHERE c.id = p_id;
  ELSE
    RAISE EXCEPTION 'Access denied: upgrade your membership to unlock this class';
  END IF;
END;
$$;

-- Grant execute to all roles: anon (logged-out) for free content, authenticated for paid
-- The functions enforce tier checks internally, so granting to anon is safe
GRANT EXECUTE ON FUNCTION public.get_recipe_content(BIGINT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_class_content(BIGINT)  TO anon, authenticated;