-- ============================================================
-- CWC+ SUPABASE COMPLETE SETUP SCRIPT
-- Run this entire script in: Supabase > SQL Editor > New Query
-- ============================================================


-- ============================================================
-- STEP 1: TABLES
-- ============================================================

-- Recipes Table
CREATE TABLE IF NOT EXISTS recipes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  author      TEXT,
  time        TEXT,
  image       TEXT,
  category    TEXT,
  difficulty  TEXT,
  rating      NUMERIC(3,1) DEFAULT 4.5,
  base_servings INTEGER DEFAULT 2,
  ingredients JSONB DEFAULT '[]'::jsonb,
  steps       JSONB DEFAULT '[]'::jsonb,
  status      TEXT DEFAULT 'published',   -- 'published' | 'draft'
  is_featured BOOLEAN DEFAULT false,
  video       TEXT,
  tier_required TEXT DEFAULT 'Free',      -- 'Free' | 'Basic' | 'Plus' | 'Premium'
  volume      TEXT DEFAULT 'CWC Original',
  scheduled_post_date TIMESTAMP WITH TIME ZONE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Classes / Masterclasses Table
CREATE TABLE IF NOT EXISTS classes (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        TEXT NOT NULL,
  instructor   TEXT,
  duration     TEXT,
  price        TEXT DEFAULT '19.99',
  image        TEXT,
  video        TEXT,
  status       TEXT DEFAULT 'published',  -- 'published' | 'draft'
  tier_required TEXT DEFAULT 'Plus',
  is_featured  BOOLEAN DEFAULT false,
  ingredients  JSONB DEFAULT '[]'::jsonb,
  steps        JSONB DEFAULT '[]'::jsonb,
  notes        TEXT,
  attachments  JSONB DEFAULT '[]'::jsonb,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Force add columns for classes and recipes
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS ingredients JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS steps JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS attachments JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS ingredients JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS steps JSONB DEFAULT '[]'::jsonb;

-- People / Users Table (linked to Supabase Auth via auth.users.id)
CREATE TABLE IF NOT EXISTS people (
  id                UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name              TEXT,
  email             TEXT UNIQUE,
  subscription_tier TEXT DEFAULT 'Free',  -- 'Free' | 'Basic' | 'Plus' | 'Premium'
  role              TEXT DEFAULT 'user',
  unlocked_volumes  TEXT[] DEFAULT '{}',
  unlocked_classes  BIGINT[] DEFAULT '{}',
  avatar_url        TEXT,
  cover_url         TEXT,
  dietary_preferences TEXT[] DEFAULT '{}',
  favorite_food     TEXT,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Force add columns in case the table already existed before the upgrade
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS unlocked_volumes TEXT[] DEFAULT '{}';
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS unlocked_classes BIGINT[] DEFAULT '{}';
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS cover_url TEXT;
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS dietary_preferences TEXT[] DEFAULT '{}';
ALTER TABLE public.people ADD COLUMN IF NOT EXISTS favorite_food TEXT;

-- Merch Table
CREATE TABLE IF NOT EXISTS merch (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  price       NUMERIC(10,2),
  image       TEXT,
  category    TEXT,
  stock       INTEGER DEFAULT 0,
  status      TEXT DEFAULT 'published',
  scheduled_post_date TIMESTAMP WITH TIME ZONE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Platform Settings Table (Key-Value Store)
CREATE TABLE IF NOT EXISTS settings (
  id         TEXT PRIMARY KEY,
  config     JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID REFERENCES auth.users(id) ON DELETE CASCADE, -- NULL means global broadcast
  type            TEXT DEFAULT 'system', -- 'system', 'class', 'shop', 'alert', 'success'
  title           TEXT NOT NULL,
  message         TEXT NOT NULL,
  attachment_type TEXT, -- 'recipe', 'class', 'none'
  attachment_id   TEXT, -- ID or URL
  read_status     BOOLEAN DEFAULT false,
  scheduled_post_date TIMESTAMP WITH TIME ZONE,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ============================================================
-- STEP 2: AUTO-CREATE USER PROFILE ON GOOGLE SIGN-IN
-- This trigger fires whenever a new user signs up via
-- Google OAuth or Email — it auto-creates their 'people' row.
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.people (id, name, email, avatar_url, subscription_tier, role)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data ->> 'full_name',
      NEW.raw_user_meta_data ->> 'name',
      split_part(NEW.email, '@', 1)
    ),
    NEW.email,
    COALESCE(
      NEW.raw_user_meta_data ->> 'avatar_url',
      NEW.raw_user_meta_data ->> 'picture'
    ),
    'Free',
    CASE WHEN NEW.email = 'ononeline30@gmail.com' THEN 'admin' ELSE 'user' END
  )
  ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Attach trigger to auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- STEP 3: ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Enable RLS on all tables
ALTER TABLE recipes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes  ENABLE ROW LEVEL SECURITY;
ALTER TABLE people   ENABLE ROW LEVEL SECURITY;
ALTER TABLE merch    ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Create is_team_member function
CREATE OR REPLACE FUNCTION public.is_team_member()
RETURNS BOOLEAN
LANGUAGE sql SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.people
    WHERE id = auth.uid() AND role IN ('admin', 'management', 'employee')
  );
$$;

-- ── RECIPES policies ─────────────────────────────────────────
-- Public can read published recipes
DROP POLICY IF EXISTS "Public can read published recipes" ON recipes;
CREATE POLICY "Public can read published recipes"
  ON recipes FOR SELECT
  USING (status = 'published');

-- Authenticated team members can do anything
DROP POLICY IF EXISTS "Admin full access to recipes" ON recipes;
CREATE POLICY "Admin full access to recipes"
  ON recipes FOR ALL
  USING (public.is_team_member());

-- ── CLASSES policies ─────────────────────────────────────────
DROP POLICY IF EXISTS "Public can read published classes" ON classes;
CREATE POLICY "Public can read published classes"
  ON classes FOR SELECT
  USING (status = 'published');

DROP POLICY IF EXISTS "Admin full access to classes" ON classes;
CREATE POLICY "Admin full access to classes"
  ON classes FOR ALL
  USING (public.is_team_member());

-- ── PEOPLE policies ──────────────────────────────────────────
-- Users can only read/update their own profile
DROP POLICY IF EXISTS "Users can view their own profile" ON people;
CREATE POLICY "Users can view their own profile"
  ON people FOR SELECT
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON people;
CREATE POLICY "Users can update their own profile"
  ON people FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Admin can view all users
DROP POLICY IF EXISTS "Admin can view all users" ON people;
CREATE POLICY "Admin can view all users"
  ON people FOR SELECT
  USING (public.is_team_member());

DROP POLICY IF EXISTS "Admin can update all users" ON people;
CREATE POLICY "Admin can update all users"
  ON people FOR UPDATE
  USING (public.is_team_member());

-- ── MERCH policies ───────────────────────────────────────────
DROP POLICY IF EXISTS "Public can read published merch" ON merch;
CREATE POLICY "Public can read published merch"
  ON merch FOR SELECT
  USING (status = 'published');

DROP POLICY IF EXISTS "Admin full access to merch" ON merch;
CREATE POLICY "Admin full access to merch"
  ON merch FOR ALL
  USING (public.is_team_member());

-- ── SETTINGS policies ────────────────────────────────────────
-- Anyone authenticated can read settings
DROP POLICY IF EXISTS "Authenticated can read settings" ON settings;
CREATE POLICY "Authenticated can read settings"
  ON settings FOR SELECT
  USING (auth.role() = 'authenticated');

-- Only admins can modify settings
DROP POLICY IF EXISTS "Admin full access to settings" ON settings;
CREATE POLICY "Admin full access to settings"
  ON settings FOR ALL
  USING (public.is_team_member());

-- ── NOTIFICATIONS policies ────────────────────────────────────────
-- Users can read their own notifications or global notifications (user_id IS NULL)
DROP POLICY IF EXISTS "Users can read their own or global notifications" ON notifications;
CREATE POLICY "Users can read their own or global notifications"
  ON notifications FOR SELECT
  USING (auth.uid() = user_id OR user_id IS NULL);

-- Users can update their own notifications (e.g. mark as read)
DROP POLICY IF EXISTS "Users can update their own notifications" ON notifications;
CREATE POLICY "Users can update their own notifications"
  ON notifications FOR UPDATE
  USING (auth.uid() = user_id);

-- Admin can manage all notifications
DROP POLICY IF EXISTS "Admin full access to notifications" ON notifications;
CREATE POLICY "Admin full access to notifications"
  ON notifications FOR ALL
  USING (public.is_team_member());


-- ============================================================
-- STEP 4: DEFAULT PLATFORM SETTINGS
-- ============================================================

INSERT INTO settings (id, config) VALUES (
  'platform',
  '{
    "siteName": "CWC+",
    "heroTitle": "Unleash Your Inner Chef",
    "maintenanceMode": false,
    "bannerEnabled": true,
    "bannerText": "New Masterclass dropping this Friday! 🚀",
    "tierPrices": { "Basic": "5.99", "Plus": "10.99", "Premium": "35.99" },
    "plugins": { "stripe": true, "mailchimp": false, "zapier": true },
    "apiKeys": []
  }'::jsonb
) ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- STEP 5: SEED SAMPLE RECIPES (DRAFTS - ADMIN ONLY)
-- ============================================================

INSERT INTO recipes (title, author, time, image, category, difficulty, rating, base_servings, ingredients, steps, status, is_featured, tier_required, volume) VALUES
(
  'Creamy Garlic Butter Pasta',
  'Chef Maria',
  '25 min',
  'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&q=80&w=800',
  'Pasta',
  'Easy',
  4.8,
  2,
  '[{"name":"Spaghetti","amount":"200g"},{"name":"Garlic cloves","amount":"4"},{"name":"Butter","amount":"60g"},{"name":"Parmesan","amount":"50g"},{"name":"Cream","amount":"100ml"},{"name":"Parsley","amount":"handful"},{"name":"Salt & pepper","amount":"to taste"}]',
  '["Boil salted water and cook spaghetti until al dente.","In a pan, melt butter and gently sauté minced garlic for 2 minutes.","Add cream and simmer for 3 minutes until slightly thickened.","Drain pasta, reserving ½ cup pasta water.","Toss pasta in the sauce, adding pasta water to loosen.","Stir in parmesan, season generously, and top with fresh parsley."]',
  'draft', true, 'Free', 'CWC Original'
),
(
  'Smoked Salmon Eggs Benedict',
  'Chef James',
  '35 min',
  'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&q=80&w=800',
  'Breakfast',
  'Medium',
  4.9,
  2,
  '[{"name":"English muffins","amount":"2"},{"name":"Smoked salmon","amount":"120g"},{"name":"Eggs","amount":"4"},{"name":"Egg yolks","amount":"3"},{"name":"Butter","amount":"150g"},{"name":"Lemon juice","amount":"1 tbsp"},{"name":"Capers","amount":"1 tbsp"},{"name":"Dill","amount":"to garnish"}]',
  '["Make hollandaise: whisk yolks over double boiler, slowly add melted butter, add lemon juice, season.","Toast muffins until golden.","Poach eggs in simmering water with a splash of vinegar for 3-4 minutes.","Layer muffin with salmon, poached egg, hollandaise.","Garnish with capers and dill. Serve immediately."]',
  'draft', true, 'Free', 'CWC Original'
),
(
  'Thai Green Curry',
  'Chef Nong',
  '40 min',
  'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&q=80&w=800',
  'Curry',
  'Medium',
  4.7,
  4,
  '[{"name":"Chicken thighs","amount":"500g"},{"name":"Coconut milk","amount":"400ml"},{"name":"Green curry paste","amount":"3 tbsp"},{"name":"Thai eggplant","amount":"200g"},{"name":"Kaffir lime leaves","amount":"4"},{"name":"Fish sauce","amount":"2 tbsp"},{"name":"Palm sugar","amount":"1 tbsp"},{"name":"Thai basil","amount":"handful"},{"name":"Jasmine rice","amount":"to serve"}]',
  '["Heat oil in wok, fry curry paste for 2 minutes until fragrant.","Add half the coconut milk, stir and cook until oil separates.","Add chicken and cook through.","Pour remaining coconut milk, add eggplant and lime leaves.","Season with fish sauce and sugar. Simmer 10 minutes.","Stir in Thai basil. Serve over jasmine rice."]',
  'draft', false, 'Free', 'CWC Original'
),
(
  'Wagyu Beef Steak with Truffle Butter',
  'Chef Antoine',
  '30 min',
  'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&q=80&w=800',
  'Mains',
  'Hard',
  5.0,
  2,
  '[{"name":"Wagyu ribeye","amount":"400g"},{"name":"Truffle butter","amount":"40g"},{"name":"Fresh thyme","amount":"4 sprigs"},{"name":"Garlic","amount":"3 cloves"},{"name":"Sea salt flakes","amount":"generous"},{"name":"Black pepper","amount":"freshly cracked"}]',
  '["Rest steak at room temp 30 mins. Pat very dry and season generously.","Heat cast iron skillet until smoking hot. Add minimal oil.","Sear 2-3 minutes each side for medium-rare.","Add butter, thyme, garlic and baste continuously for 90 seconds.","Rest on a wire rack for 8 minutes — critical step.","Slice against the grain. Top with truffle butter. Serve immediately."]',
  'draft', true, 'Premium', 'Volume 2'
),
(
  'Matcha Soufflé Pancakes',
  'Chef Yuki',
  '45 min',
  'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&q=80&w=800',
  'Desserts',
  'Hard',
  4.6,
  2,
  '[{"name":"Egg yolks","amount":"2"},{"name":"Egg whites","amount":"3"},{"name":"Matcha powder","amount":"2 tsp"},{"name":"Milk","amount":"2 tbsp"},{"name":"Flour","amount":"4 tbsp"},{"name":"Baking powder","amount":"½ tsp"},{"name":"Caster sugar","amount":"3 tbsp"},{"name":"Cream of tartar","amount":"¼ tsp"}]',
  '["Whisk yolks, milk, matcha, flour and baking powder until smooth.","Whip egg whites with cream of tartar until foamy, add sugar gradually to stiff peaks.","Gently fold ⅓ whites into yolk mixture, then fold in remaining.","Heat pan on lowest setting, lightly grease. Spoon batter into tall rounds.","Cook 4-5 min with lid on. Gently flip. Cook 3 more minutes.","Stack high, dust with matcha, serve with whipped cream."]',
  'draft', false, 'Plus', 'Volume 1'
)
ON CONFLICT DO NOTHING;


-- ============================================================
-- STEP 6: SEED SAMPLE MASTERCLASSES (DRAFTS - ADMIN ONLY)
-- ============================================================

INSERT INTO classes (title, instructor, duration, price, image, status, tier_required) VALUES
(
  'The Art of French Sauces',
  'Chef Antoine Dubois',
  '1h 45m',
  '24.99',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=80&w=800',
  'draft',
  'Plus'
),
(
  'Japanese Knife Skills & Sushi',
  'Chef Hiroshi Tanaka',
  '2h 10m',
  '29.99',
  'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=800',
  'draft',
  'Plus'
),
(
  'Baking Masterclass: Sourdough',
  'Chef Emma Wilson',
  '1h 30m',
  '19.99',
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
  'draft',
  'Basic'
),
(
  'Modern Pastry & Plating',
  'Chef Sophie Laurent',
  '2h 00m',
  '34.99',
  'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800',
  'draft',
  'Premium'
)
ON CONFLICT DO NOTHING;

-- ============================================================
-- STORAGE & NEW FIELDS FOR CLASS SCHEDULES
-- ============================================================
-- Create the storage bucket for public assets if it doesn't exist
INSERT INTO storage.buckets (id, name, public) 
VALUES ('public-assets', 'public-assets', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'public-assets');

DROP POLICY IF EXISTS "Allow Uploads" ON storage.objects;
CREATE POLICY "Allow Uploads" 
ON storage.objects FOR INSERT 
WITH CHECK (bucket_id = 'public-assets');

DROP POLICY IF EXISTS "Allow Updates" ON storage.objects;
CREATE POLICY "Allow Updates" 
ON storage.objects FOR UPDATE 
USING (bucket_id = 'public-assets');

DROP POLICY IF EXISTS "Allow Deletes" ON storage.objects;
CREATE POLICY "Allow Deletes" 
ON storage.objects FOR DELETE 
USING (bucket_id = 'public-assets');

-- Add new Date fields to classes
ALTER TABLE classes 
ADD COLUMN IF NOT EXISTS scheduled_post_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS live_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS notes TEXT;

-- Add new fields to recipes
ALTER TABLE recipes
ADD COLUMN IF NOT EXISTS video TEXT,
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS scheduled_post_date TIMESTAMP WITH TIME ZONE;

-- Add new fields to merch
ALTER TABLE merch
ADD COLUMN IF NOT EXISTS scheduled_post_date TIMESTAMP WITH TIME ZONE;

-- Add new fields to notifications
ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS scheduled_post_date TIMESTAMP WITH TIME ZONE;

-- Add new fields to people
ALTER TABLE people
ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';

-- Ensure god admin has the admin role (for existing accounts before the trigger was added)
UPDATE public.people 
SET role = 'admin' 
WHERE email = 'ononeline30@gmail.com';

-- ============================================================
-- DONE!
-- ============================================================
-- Next steps after running this script:
-- 1. Go to Supabase Dashboard > Authentication > Providers > Google
-- 2. Enable Google provider & enter your Google OAuth credentials
-- 3. Add redirect URL: https://your-project.supabase.co/auth/v1/callback
-- 4. In Authentication > URL Configuration, add:
--    - http://localhost:5173/auth/callback  (local dev)
--    - https://yourdomain.com/auth/callback (production)
-- ============================================================
