-- =========================================================
-- CWC+ VOLUME 17 - PRODUCTION UPSERT SQL INGESTION SCRIPT
-- Generated on May 2026
-- =========================================================

BEGIN;


-- Insert / Update recipe: Chocolate Cupcakes (ID: 269)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    269,
    'Chocolate Cupcakes',
    'Desserts',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "secukupnya", "unit": "", "name": "CHOCOLATE CUPCAKES (TANPA TELUR)"}, {"amount": "1\u00bd", "unit": "cawan", "name": "Tepung gandum (200 g)"}, {"amount": "1", "unit": "cawan", "name": "Gula (200 g)"}, {"amount": "\u00bd", "unit": "cawan", "name": "Serbuk koko (50 g)"}, {"amount": "1", "unit": "sudu kecil", "name": "Baking powder"}, {"amount": "\u00bc", "unit": "sudu kecil", "name": "Baking soda"}, {"amount": "\u00bc", "unit": "sudu kecil", "name": "Garam"}, {"amount": "\u00bd", "unit": "cawan", "name": "Minyak masak (125 ml)"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "Esen vanila"}, {"amount": "1", "unit": "sudu kecil", "name": "Serbuk kopi"}, {"amount": "2", "unit": "sudu besar", "name": "Air panas mendidih"}, {"amount": "1", "unit": "cawan  ATAU 1 cawan susu + 1 sudu besar jus lemon / cuka (Kacau dan biarkan >5 minit)", "name": "Buttermilk (250 ml)"}]'::jsonb,
    '["Panaskan oven pada suhu 170\u00b0C-180\u00b0C. Set oven api atas bawah. Off kipas jika boleh.", "Sediakan loyang cupcake dengan paper liner.", "Dalam satu mangkuk, ayak dan gaul tepung, serbuk koko,, baking powder, baking soda dan garam.", "Dalam mangkuk lain, campurkan minyak, gula, esen vanila dan buttermilk. Gaul sehingga gula larut.", "Jika guna kopi, larutkan serbuk kopi dengan air panas, kemudian masukkan ke bahan basah.", "Satukan bahan basah ke dalam bahan kering. Gaul perlahan hingga sebati (jangan overmix).", "Tuang adunan ke dalam paper liner sehingga \u00be penuh.", "Bakar di rak tengah selama 18\u201325 minit atau sehingga lidi keluar bersih.", "Sejukkan sebelum dihias atau dihidang."]'::jsonb,
    '["Serbuk kopi hanya untuk menaikkan rasa coklat, tidak beri rasa kopi pada cupcake."]'::jsonb,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Easy Chocolate Whipped Cream (ID: 270)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    270,
    'Easy Chocolate Whipped Cream',
    'Desserts',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "1", "unit": "cup", "name": "heavy cream/whipping cream sejuk dari chiller)"}, {"amount": "\u2153- \u00bd", "unit": "cup", "name": "powdered sugar (boleh kurangkan ke \u00be cup jika tak suka manis)"}, {"amount": "2", "unit": "sudu besar", "name": "cocoa powder (guna cocoa powder berkualiti)"}]'::jsonb,
    '["Ayak powdered sugar + cocoa powder (penting supaya tak berketul).", "Dalam mangkuk sejuk, masukkan heavy cream/whipping cream.", "Pukul kelajuan sederhana hingga mula pekat.", "Masukkan campuran gula + cocoa sedikit demi sedikit.", "Teruskan pukul hingga soft\u2013stiff peaks. Jangan overbeat, nanti cream boleh pecah."]'::jsonb,
    '["Jika rasa terlalu pahit, tambah 1 sudu besar powdered sugar.", "Untuk rasa lebih coklat & berkilat, boleh tambah 1 sudu besar coklat cair (dark/milk) yang dah sejuk.", "Untuk lebih stabil (cupcake / piping lama)- Tambah 1 tsp gelatin + 1 tbsp air panas (tunggu biar suam, baru masukkan masa whipping)"]'::jsonb,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Crispy Cheese Scallion Pancake (ID: 271)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    271,
    'Crispy Cheese Scallion Pancake',
    'Desserts',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan Doh \u2014", "amount": "", "unit": ""}, {"amount": "150", "unit": "g", "name": "Tepung gandum (1 cup padat)"}, {"amount": "1.5", "unit": "g", "name": "Garam (\u00bc tsp)"}, {"amount": "95", "unit": "ml", "name": "Air"}, {"name": "\u2014 Bahan Inti (filling) \u2014", "amount": "", "unit": ""}, {"amount": "30", "unit": "g", "name": "Daun bawang (hiris halus)"}, {"amount": "50", "unit": "g  mozarella/cheddar", "name": "Cheese (parut)"}, {"amount": "secukupnya", "unit": "", "name": "Baking soda (secubit)"}, {"amount": "20", "unit": "g", "name": "Butter (cairkan)"}, {"name": "\u2014 Bahan Lain: Minyak Secukupnya \u2014", "amount": "", "unit": ""}]'::jsonb,
    '["Masukkan tepung gandum dan garam dalam mangkuk.", "Tuang air sedikit demi sedikit sambil uli sehingga jadi doh lembut & tidak melekat di tangan.", "Tutup doh dengan plastik atau kain lembap dan rehatkan 10 minit.", "Campurkan daun bawang dan baking soda dalam mangkuk. Gaul rata.", "Parut cheese dan ketepikan.", "Cairkan butter. Ketepikan. Cara sediakan Bancuhan Tepung Tabur Semasa Roll", "Gaul tepung gandum dan tepung jagung (\u00bd cawan masing-masing) hingga sebati.", "Tabur di permukaan kerja dan di atas doh semasa canai supaya tidak melekat.", "Bahagi doh kepada 4 bebola.", "Tabur sedikit bancuhan tepung tabur atas permukaan kerja.", "Canai doh menjadi bulat nipis. Anggaran 25-28cm diameter.", "Sapu butter rata di atas doh.", "Tabur filling daun bawang dan cheese ratakan.", "Lipat doh seperti buat mertabak. Sapu butter sebelum lipat lagi sehingga semua bahagian tertutup kemas.", "Ulang sehingga selesai.", "Panaskan minyak sedikit dalam kuali.", "Goreng/masak pancake dengan api sederhana hingga keemasan & rangup, Anggaran 2 minit setiap bahagian.", "Angkat, toskan minyak. Siap."]'::jsonb,
    NULL,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Simple Pancake Dipping Sauce (ID: 272)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    272,
    'Simple Pancake Dipping Sauce',
    'Desserts',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "1", "unit": "batang", "name": "daun bawang (hiris nipis)"}, {"amount": "\u00bd", "unit": "sudu besar", "name": "red pepper flakes"}, {"amount": "\u00bd", "unit": "", "name": "cili merah (hiris & cincang halus)"}, {"amount": "1", "unit": "ulas", "name": "bawang putih (cincang halus)"}, {"amount": "2", "unit": "sudu besar", "name": "kicap cair"}, {"amount": "1", "unit": "sudu besar", "name": "air"}, {"amount": "1", "unit": "sudu kecil", "name": "gula atau madu"}, {"amount": "\u00bd", "unit": "sudu besar", "name": "biji sesame"}, {"amount": "\u00bd", "unit": "sudu besar", "name": "minyak bijan"}]'::jsonb,
    '["Masukkan daun bawang, cili dan bawang putih dalam mangkuk kecil.", "Tambah kicap, air, gula/madu, biji sesame, minyak bijan & red pepper flakes.", "Gaul rata sampai gula/madu larut.", "Siap untuk dicelup pancake."]'::jsonb,
    NULL,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Kuah Lada CWC (ID: 273)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    273,
    'Kuah Lada CWC',
    'Sides',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan Tumis Awal: Minyak Masak Secukupnya \u2014", "amount": "", "unit": ""}, {"amount": "\u00bc", "unit": "sudu kecil", "name": "biji sawi"}, {"amount": "\u00bc", "unit": "sudu kecil", "name": "halba"}, {"amount": "1", "unit": "", "name": "tangkai daun kari"}, {"amount": "secukupnya", "unit": "", "name": "Tumis sampai biji sawi meletup & daun kari garing sikit (api sederhana)."}, {"name": "\u2014 Bahan Kisar \u2014", "amount": "", "unit": ""}, {"amount": "10", "unit": "biji", "name": "bawang merah"}, {"amount": "4", "unit": "ulas", "name": "bawang putih"}, {"amount": "1", "unit": "", "name": "inci halia"}, {"amount": "15", "unit": "biji cili kering", "name": "1 ketul besar kunyit hidup 10 (rendam, buang biji)"}, {"amount": "1", "unit": "sudu kecil", "name": "lada hitam"}, {"amount": "1", "unit": "sudu kecil", "name": "jintan putih"}, {"amount": "1", "unit": "", "name": "inci belacan bakar Sedikit air"}, {"name": "\u2014 Bahan Lain \u2014", "amount": "", "unit": ""}, {"amount": "4-5", "unit": "keping", "name": "Ikan pilihan (Tenggiri/jenahak,pari etc)"}, {"amount": "secukupnya", "unit": "", "name": "1 batang serai (diketuk Air secukupnya Air asam jawa pekat  Bendi secukupnya)"}, {"amount": "2", "unit": "biji", "name": "Tomato (optional) Garam secukup rasa Sedikit gula (optional, jika perlu) Air secukupnya (untuk kuah) KUAH LADA CWC"}]'::jsonb,
    '["Panaskan minyak, masukkan biji sawi bila meletup terus masukkan daun kari dan halba. Tumis sampai bunyi letup-letup & wangi. Sekejap sahaja.", "Masukkan bahan kisar, dan serai tumis lama sampai betul-betul pecah minyak. Masukkan sedikit air sebanyak 2x untuk garingkan cili.", "Bila cili sudah garing dan pecah minyak, masukkan air asam jawa dan bendi, biar mendidih. Tambah air secukupnya untuk kuah. Tunggu bendi sedikit lembut.", "Seterusnya, masukkan ikan, kecilkan api, biar masak perlahan. Jangan kacau kuah selepas masuk ikan.", "Akhir sekali masukkan tomato jika ada.", "Perasakan garam (dan sikit gula jika perlu). Rasa suaikan dengan citarasa. Tutup api. Resting kuah sebelum hidang."]'::jsonb,
    NULL,
    '["sides", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Creamy Spicy Ramen Express (ID: 274)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    274,
    'Creamy Spicy Ramen Express',
    'Desserts',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "550", "unit": "ml", "name": "air"}, {"amount": "1", "unit": "paket", "name": "Shin Ramen (guna sekali dengan perencah)"}, {"amount": "1", "unit": "sudu besar", "name": "peanut butter"}, {"amount": "\u00bd", "unit": "sudu besar", "name": "serbuk cili Korea (gochugaru) (optional) Segenggam tauge hijau segar / dicelur (optional)"}, {"amount": "1", "unit": "batang", "name": "daun bawang, hiris (untuk hiasan)"}, {"amount": "1", "unit": "biji", "name": "telur rebus (jika ada)"}]'::jsonb,
    '["Didihkan air dalam periuk. Masukkan mi ramen bersama perencah. Masak selama 4 minit 30 saat atau hingga ramen lembut", "Masukkan peanut butter dan gochugaru (jika guna). Kacau hingga kuah sebati dan sedikit berkrim.", "Tuang ke dalam mangkuk hidangan.", "Taburkan tauge dan daun bawang di atas.", "Hidangkan panas dan nikmati \ud83c\udf36 \ud83c\udf5c"]'::jsonb,
    '["Tambah 1 sudu kecil minyak bijan untuk aroma.", "Letak telur separuh masak kalau nak lebih padu.", "Boleh adjust peanut butter ikut tahap creamy yang diinginkan."]'::jsonb,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Chewy Fruity Cookies (ID: 275)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    275,
    'Chewy Fruity Cookies',
    'Desserts',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "185", "unit": "g", "name": "tepung gandum serbaguna (\u00b1 1\u00bd cawan)"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "baking soda"}, {"amount": "\u00bc", "unit": "sudu kecil", "name": "garam"}, {"amount": "115", "unit": "g", "name": "mentega tanpa garam (\u00bd cawan, dilembutkan)"}, {"amount": "100", "unit": "g", "name": "gula perang (\u00bd cawan, dipadatkan)"}, {"amount": "100", "unit": "g", "name": "gula putih (\u00bd cawan)"}, {"amount": "1", "unit": "biji", "name": "telur"}, {"amount": "1", "unit": "sudu kecil", "name": "esen vanila"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "serbuk kayu manis / \u00bc sudu kecil jika guna all spice powder \u215b sudu kecil serbuk buah pala (nutmeg) atau all spice powder Parutan kulit 1 biji oren/lemon"}, {"amount": "240", "unit": "g", "name": "campuran buah kering & kekacang (kismis, mixed fruits, cranberry, aprikot kering, wallnuts)"}]'::jsonb,
    '["Pukul mentega, gula perang dan gula putih hingga kembang dan pucat (\u00b1 3\u20134 minit).", "Masukkan serbuk kayu manis, serbuk buah pala, parutan kulit oren dan esen vanila. Tekstur perlu jadi lembut macam krim.", "Masukkan telur dan pukul sekadar sebati sahaja. Jangan overmix \u2014 jika terlalu lama, cookies akan jadi lebih ke arah kek, bukan chewy.", "Masukkan semua buah kering dan kekacang. Gaul perlahan guna spatula hingga rata.", "Ayak dan gaul tepung gandum, baking soda dan garam dalam bekas berasingan. Masukkan ke dalam adunan basah sedikit demi sedikit. Gaul pada kelajuan perlahan sehingga sebati. CHEWY FRUITY COOKIES", "Rehatkan Doh. Simpan doh dalam peti sejuk selama 20 minit. Ini bantu cookies tak melebar berlebihan dan kekal tebal & chewy.", "Panaskan oven pada 175\u00b0C. Alas dulang dengan baking paper.", "Scoop doh 1 sudu besar penuh, jarakkan \u00b1 2 inci.", "Bakar selama 15\u201316 minit hingga bahagian tepi keperangan ringan.", "Bahagian tengah nampak lembut \u2013 itu normal.", "Biarkan atas dulang 5 minit, cookies akan mendap sedikit dan jadi lebih kenyal di tengah.", "Alihkan ke rak dawai selepas dan sejuk sepenuhnya. Siap."]'::jsonb,
    NULL,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Keladi Swiss Roll (ID: 276)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    276,
    'Keladi Swiss Roll',
    'Desserts',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "3", "unit": "Biji", "name": "telur gred A/B Bancuhan Telur Kuning"}, {"amount": "20", "unit": "g setiap satu) \u2013 suhu bilik", "name": "3 biji egg yolk (\u00b118"}, {"amount": "15", "unit": "g", "name": "gula kastor"}, {"amount": "27", "unit": "ml", "name": "susu segar"}, {"amount": "27", "unit": "ml", "name": "minyak sayuran/masak"}, {"amount": "1", "unit": "tsp", "name": "Emulco keladi"}, {"amount": "\u00bd", "unit": "tsp", "name": "esen vanila"}, {"amount": "secukupnya", "unit": "", "name": "20g tepung gandum (all (purpose flour))"}, {"amount": "20", "unit": "g", "name": "tepung jagung (corn starch)"}, {"amount": "secukupnya", "unit": "", "name": "(Optional) 1 titik pewarna ungu / lavender Bancuhan Telur Putih"}, {"amount": "35", "unit": "g setiap satu) \u2013 suhu bilik", "name": "3 biji egg white (\u00b130"}, {"amount": "secubit", "unit": "", "name": "garam"}, {"amount": "40", "unit": "g", "name": "gula kastor B. Filling Keladi"}, {"amount": "secukupnya", "unit": "", "name": "240 ml whipping cream (sejuk) (dairy)"}, {"amount": "3", "unit": "Tbsp", "name": "gula aising"}, {"amount": "1", "unit": "tsp", "name": "Emulco keladi"}, {"amount": "secukupnya", "unit": "", "name": "(Optional) 1 titik pewarna ungu"}, {"amount": "secukupnya", "unit": "", "name": "Jika guna non dairy whipping cream tak perlu tambah gula bahan lain masih sama."}]'::jsonb,
    '["Pastikan mangkuk & whisk bersih, kering dan bebas minyak.", "Pukul egg white bersama garam hingga berbuih.", "Masukkan gula sedikit demi sedikit.", "Teruskan pukul hingga stiff peak (puncak keras & tak jatuh). Anggaran 6minit.", "Dalam mangkuk lain, kacau egg yolk dan gula hingga sebati.", "Masukkan susu, minyak, esen vanila dan Emulco keladi.", "Ayakkan tepung gandum dan tepung jagung.", "Kacau hingga adunan licin dan tidak berketul.", "Ambil \u2153 adunan egg white, masukkan ke dalam adunan yolk untuk ringankan adunan.", "Masukkan baki egg white dan fold perlahan-lahan hingga sebati.", "Jangan overmix supaya kek kekal ringan.", "Panaskan oven pada 160\u00b0C", "Oles loyang dan alas dengan baking paper. Tuang adunan ke dalam loyang 10 \u00d7 10 inci atau loyang yang bersesuaian. Ratakan permukaan.", "Bakar selama 25-30 minit Kek siap bila, permukaan tidak merekah.", "Bila ditekan, kek kenyal & naik semula. Biarkan kek sejuk dalam tray selama 5minit. Kemudian terbalikkan atas baking paper. Sejukkan. KELADI SWISS ROLL", "Pukul whipping cream, gula aising dan Emulco keladi hingga soft\u2013 medium peak. Jika guna whipping cream yang non-dairy tak perlu tambah gula.", "Bila kek sudah sejuk. Sapu filling dan ratakan.", "Gulung kemas menggunakan baking paper.", "Simpan dalam peti sejuk 30minit sebelum dipotong."]'::jsonb,
    NULL,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Ayam Goreng Tomyam Thai (ID: 277)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    277,
    'Ayam Goreng Tomyam Thai',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "secukupnya", "unit": "", "name": "6 ulas bawang putih (ditumbuk kasar)"}, {"amount": "secukupnya", "unit": "", "name": "2 biji bawang merah (ditumbuk kasar)"}, {"amount": "7-10", "unit": "", "name": "tangkai cili padi merah + cili hijau \u2013 ditumbuk kasar"}, {"amount": "1", "unit": "sudu makan", "name": "pes tomyam"}, {"amount": "secukupnya", "unit": "", "name": "2 batang serai (diketuk Garam & gula secukup rasa)"}, {"amount": "1-2", "unit": "biji", "name": "jus limau nipis (ikut citarasa) Bunga kubis secukupnya/ sayur pilihan (jika ada)"}, {"amount": "1", "unit": "biji", "name": "tomato Lobak merah (potong nipis/ikut citarasa)"}, {"amount": "secukupnya", "unit": "", "name": "500gm Ayam goreng (Potong kecil) (lemur dengan kunyit garam.)"}]'::jsonb,
    '["Panaskan sedikit minyak dalam kuali. Goreng ayam sehingga masak dan sedikit garing. Angkat dan toskan.", "Dalam kuali yang sama, tumis bawang putih, bawang merah, dan cili yang telah dikisar sehingga naik bau dan bawang menjadi sedikit perang.", "Masukkan 1 sudu makan pes tomyam ke dalam kuali, kacau rata sehingga sebati. Naik bau.", "Masukkan serai dan daun limau. Tumis sampai naik bau.", "Tambahkan garam dan gula secukup rasa. Kacau rata. Jika suka, boleh tambah sedikit air untuk jadikan kuah sikit. Masukkan lobak merah dan kobis bunga. Kacau.", "Masukkan ayam yang telah digoreng tadi ke dalam kuali bersama buah tomato. Gaul rata supaya ayam disalut dengan pes tomyam.", "Tutup api. Perah jus limau nipis ke atas ayam dan kacau sekejap untuk rasa lebih segar. Resting kan seketika. Siap."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Sayur Petola Tumis Air (ID: 278)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    278,
    'Sayur Petola Tumis Air',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "1", "unit": "", "name": "Petola, di potong bulat tak tebal tak nipis Lobak merah, dihiris nipis (julienne) Cili merah/ hijau besar, dihiris serong Sedikit ikan bilis (ditumbuk)"}, {"amount": "3", "unit": "ulas", "name": "bawang putih (ditumbuk)"}, {"amount": "2", "unit": "biji", "name": "bawang merah (ditumbuk)"}, {"amount": "500", "unit": "ml) Serbuk lada hitam secukup rasa Perasa", "name": "2 biji telur Sohun, direndam sekejap dalam air suam sehingga lembut Fucuk, direndam dan tos Sedikit air (sekitar 400 (contohnya garam atau secukup rasa)"}]'::jsonb,
    '["Rendam sohun dan fucuk dalam air suam, hiris sayur-sayuran, bawang dan cili.", "Panaskan sedikit minyak dalam kuali. Tumis bawang merah dan bawang putih sehingga wangi.", "Masukkan carrot, petola dan cili. Masukkan air. renehkan selama 2-3 minit. Sehingga mendidih.", "Masukkan sohun dan fucuk yang telah direndam. Kacau rata.", "Tambah air & perasa: Masukkan sedikit air supaya sayur lebih lembut. Perasakan dengan serbuk lada hitam dan perasa secukupnya.", "Pecahkan telur. Biarkan telur set dahulu baru kacau perlahan.", "Tutup kuali/periuk dan masak 2-3 minit supaya semua bahan sebati.", "Siap untuk dihidang: Angkat dan hidangkan panas-panas."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Pad Thai CWC (ID: 279)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    279,
    'Pad Thai CWC',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "3", "unit": "sudu besar", "name": "air"}, {"amount": "3", "unit": "sudu besar", "name": "pes asam jawa"}, {"amount": "2", "unit": "sudu besar", "name": "sos ikan"}]'::jsonb,
    '["Masukkan gula ke dalam periuk kecil dan panaskan atas api sederhana.", "Kacau hingga gula cair dan warnanya menjadi sedikit gelap.", "Terus masukkan air, sos ikan dan pes asam jawa.", "Didihkan perlahan (simmer), kemudian tutup api.", "Biarkan sos berehat sementara menyediakan bahan lain.", "Pastikan gula telah larut sepenuhnya sebelum digunakan.", "Bahan Utama: 100-150g mee beras kering Kway Teow jenis kering saiz sederhana (direndam air suhu bilik 30minit)", "3 sudu besar udang kering (dicincang kasar)", "3 ulas bawang putih (dicincang)", "\u00bc cawan bawang merah (dicincang kasar)", "100 g tofu keras / pressed tofu (dipotong kecil) Serbuk cili kering (ikut tahap pedas)", "3 sudu besar minyak sayuran/masak", "10 ekor udang sederhana (atau protein pilihan)", "1-2 biji telur", "2\u00bd cawan taugeh", "7 batang kucai bawang putih (dipotong \u00b15 cm)", "\u00bc cawan kacang tanah panggang (ditumbuk kasar)", "1 biji limau nipis PAD THAI CWC", "Rendam mee beras dalam air suhu bilik sehingga lembut lentur. 1jam.", "Toskan mee dan jika suka boleh gunting supaya mee menjadi separuh panjang. Mudah nak makan.", "Campurkan tofu, bawang putih, bawang merah, lobak jeruk manis, udang kering, serbuk cili.", "Panaskan kuali / wok atas api besar.", "Masukkan sedikit minyak. Goreng udang sehingga hampir masak, angkat dan ketepikan.", "Dalam kuali yang sama, kecilkan api ke sederhana.", "Tambah sedikit minyak jika perlu. Masukkan campuran tofu dan tumis hingga bawang putih keperangan dan bawang merah layu. Besarkan api.", "Masukkan mee dan tuang sos Pad Thai. Kacau pantas sehingga sos meresap sepenuhnya ke dalam mee. Anggaran 1 minit. Jika mee masih keras, percik sedikit air dan teruskan memasak.", "Tolak mee ke satu bahagian kuali. Tambah sedikit minyak di ruang kosong. Pecahkan telur dan kacau kuning telur. Tindihkan mee di atas telur dan biarkan \u00b130 saat.", "Terbalikkan dan gaul sehingga telur sebati. Masukkan semula udang bersama jusnya.", "Masukkan taugeh, kucai dan separuh kacang tanah.", "Tutup api dan gaul perlahan sehingga sebati."]'::jsonb,
    '["Mee boleh direndam awal dan disimpan dalam peti sejuk.", "Jika guna ayam / daging, perap ringan dengan sos ikan atau kicap.", "Sos Pad Thai boleh dibuat awal dan tahan lama dalam peti sejuk.", "Disarankan masak 2\u20133 hidangan sahaja sekali masak supaya mee tidak lembik."]'::jsonb,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Express Banana Pancakes (Thai Roti) (ID: 280)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    280,
    'Express Banana Pancakes (Thai Roti)',
    'Desserts',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan Doh \u2014", "amount": "", "unit": ""}, {"amount": "150", "unit": "g", "name": "Tepung gandum (1 cup padat)"}, {"amount": "\u00bc", "unit": "tsp", "name": "Garam"}, {"amount": "1\u00bd", "unit": "sudu besar", "name": "Gula pasir halus"}, {"amount": "95", "unit": "ml", "name": "Air"}, {"amount": "20", "unit": "g", "name": "Butter (cairkan/lembutkan)"}, {"name": "\u2014 Bahan Lain: Minyak Secukupnya \u2014", "amount": "", "unit": ""}]'::jsonb,
    '["Cairkan butter. Ketepikan. Cara sediakan Bancuhan Tepung Tabur Semasa Roll", "Gaul tepung gandum dan tepung jagung hingga sebati.", "Tabur di permukaan doh semasa canai.", "Masukkan tepung gandum, gula dan garam dalam mangkuk.", "Tuang air sedikit demi sedikit sambil uli sehingga jadi doh lembut & tidak melekat di tangan. 3-4minit.", "Tutup doh dengan plastik atau kain lembap dan rehatkan 15 minit.", "Selepas rehat, buat teknik slap & fold beberapa kali sehingga doh jadi lebih licin dan tidak melekat. EXPRESS BANANA PANCAKES", "Bahagi doh kepada 4 bebola. Masukkan 4\u20135 sudu besar minyak ke dalam mangkuk kecil yang dalam.", "Sapu sedikit minyak pada tangan. Leperkan setiap bebola doh menjadi bulat kecil (\u00b1 5 cm diameter).", "Masukkan doh leper ke dalam minyak dan pastikan ia bersalut minyak.", "Tutup dan rehatkan selama 10 minit. Rehat dalam minyak membantu gluten relaks dan memudahkan doh ditarik nipis tanpa koyak.", "Tabur sedikit bancuhan tepung tabur atas permukaan kerja.", "Canai doh. Jangan canai terlalu nipis di bahagian tengah (mudah bocor bila letak pisang).", "Sapu butter di atas doh, untuk hasil lapisan jadi rangup & wangi.", "Letakkan pisang di tengah doh.", "Lipat doh seperti buat mertabak. Sapu butter sebelum lipat lagi sehingga semua bahagian tertutup kemas. Ulang sehingga selesai.", "Panaskan minyak sedikit dalam kuali. Minyak dalam kuali cukup sapu dasar sahaja, bukan deep fry.", "Set api sederhana untuk elak cepat hangus (especially jika doh manis)", "Masak pancake hingga keemasan & rangup, Anggaran 2 minit setiap bahagian.", "Angkat. Kemudian, ambil susu pekat sapu atau drizzle atas permukaan pancake. Boleh juga tabur gula kasar pada permukaan pancake. Siap."]'::jsonb,
    NULL,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Ayam Goreng Pedas Manis Ala Korean (ID: 281)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    281,
    'Ayam Goreng Pedas Manis Ala Korean',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan: Topping & Lain-lain \u2014", "amount": "", "unit": ""}, {"amount": "20", "unit": "g", "name": "Kacang (dicincang kasar)"}, {"amount": "secukupnya", "unit": "", "name": "Biji bijan (secukupnya)"}, {"amount": "secukupnya", "unit": "", "name": "Serbuk daun parsli (secukupnya)"}, {"amount": "secukupnya", "unit": "", "name": "Minyak masak (\u00b11 liter A. Ayam & Perapan)"}, {"amount": "350", "unit": "g", "name": "Isi ayam (breast / tenderloin)"}, {"amount": "100", "unit": "ml", "name": "Susu segar"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "Garam (3g)"}, {"amount": "\u00bc", "unit": "sudu kecil", "name": "Serbuk lada hitam (1g)"}, {"amount": "\u00bc", "unit": "sudu kecil", "name": "Serbuk kari (1g)"}]'::jsonb,
    '["Basuh ayam dan toskan air hingga kering.", "Potong ayam kepada saiz sederhana (bite-sized).", "Masukkan garam, lada hitam dan serbuk kari. Gaul rata.", "Tuang susu sehingga ayam tenggelam.", "Perap selama 15\u201330 minit. B. Sos Ayam Korea (Seasoned Chicken Sauce)", "Corn syrup / madu \u2013 110g (\u00bd cawan)", "Sos tomato (ketchup) \u2013 3 sudu besar (35g)", "Pes cili Korea (gochujang) \u2013 1 sudu besar (20g)", "Kicap soya \u2013 1\u00bd sudu besar (17g)", "Bawang putih cincang \u2013 2 sudu besar (30g)", "Serbuk cili \u2013 1 sudu kecil (7g)", "Gula \u2013 2 sudu besar (25g)", "Masukkan semua bahan sos ke dalam periuk kecil.", "Masak dengan api perlahan, kacau sentiasa.", "Biarkan mendidih dan pekat selama 3\u20135 minit.", "Tutup api dan ketepikan. AYAM GORENG PEDAS MANIS ALA KOREAN", "C. Tepung Goreng (Homemade Frying Powder) - Gaul & ayak rata", "Tepung gandum \u2013 150g", "Tepung kanji kentang (potato starch) \u2013 50g", "Garam \u2013 1 sudu kecil (4g)", "Baking powder \u2013 \u00bd sudu kecil (2g)", "Serbuk lada hitam \u2013 \u00bc sudu kecil (1g) Ambil 70g (\u00bd cawan) untuk batter pertama (basah) Ambil 70g (\u00bd cawan) untuk batter kedua (kering)", "Masukkan batter pertama- basah (70g tepung goreng) ke dalam ayam yang diperap . Gaul hingga bersalut.", "Masukkan batter kedua-kering (70g tepung goreng) ke dalam beg plastik.", "Masukkan ayam ke dalam beg dan goncang hingga bersalut sekata.", "Panaskan minyak hingga suhu 170\u00b0C. Set api sederhana kuat.", "Goreng ayam hingga keemasan dan rangup. Anggaran 3minit.", "Angkat dan toskan minyak. Rehatkan selama 1 minit.", "Kemudian, buka api kuat goreng sekali lagi sehingga golden brown. 1minit Tip rangup: Goreng dua kali (double fry) untuk hasil lebih rangup & tahan lama.", "Masukkan ayam goreng ke dalam mangkuk besar.", "Tuangkan sos ayam Korea dan masukkan kacang.", "Gaul perlahan hingga semua ayam disaluti sos.", "Taburkan bijan dan parsli sebagai hiasan. Siap."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Asam Pedas Paling Mudah (ID: 282)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    282,
    'Asam Pedas Paling Mudah',
    'Mains',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "1", "unit": "", "name": "inci belacan bakar"}, {"amount": "8", "unit": "biji", "name": "bawang merah/ 3 biji bawang besar"}, {"amount": "4", "unit": "ulas", "name": "bawang putih"}, {"amount": "1", "unit": "", "name": "inci halia"}, {"amount": "1", "unit": "", "name": "inci kunyit hidup"}, {"amount": "1", "unit": "cawan", "name": "air"}]'::jsonb,
    '["Kisar semua bahan di atas sehingga halus.", "Bahan Lain: Minyak masak secukupnya", "1 batang serai (dititik)", "4 cawan air (secukupnya) Garam secukupnya Pes asam jawa /air asam jawa (secukupnya)", "1 sudu besar lada hitam (tumbuk kasar)", "3kg-1.5kg ikan (pari / tenggiri / kembung / jenahak/siakap)", "1 ikat daun kesum", "1 kuntum bunga kantan (belah dua)", "10 biji bendi (secukupnya)", "2 biji tomato (belah empat) ASAM PEDAS PALING MUDAH", "Panaskan minyak dalam periuk. Tumis bahan kisar bersama serai hingga naik bau, cili masak dan minyak mula pecah.", "Masukkan air, kacau dan biarkan mendidih 5\u201310 minit supaya kuah betul- betul naik rasa.", "Masukkan pes asam jawa, garam & lada hitam. Kacau dan rasa kuah (boleh tambah asam/garam ikut selera).", "Masukkan bendi, daun kesum & bunga kantan, masak 3minit. Kemudian, masukkan ikan, kecilkan api. Jangan kacau kuat, supaya ikan tak hancur. Biar mereneh seketika.", "Akhir sekali masukkan tomato. Masak sekejap hingga tomato lembut.", "Tutup api dan restingkan dulu. Kuah akan bertambah pekat. Sedia untuk dihidang."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Cincalok Mudah (ID: 283)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    283,
    'Cincalok Mudah',
    'Sides',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "5", "unit": "biji cili padi  2\u20133 biji bawang merah (hiris nipis) 1\u20132 biji limau kasturi/limau nipis (ambil jus)", "name": "1 cawan cencalok siap beli 3 (ikut pedas)"}]'::jsonb,
    '["Tapiskan cencaluk, supaya kurang masin.", "Dalam mangkuk, masukkan cencalok, bawang yang telah dihiris.", "Perah limau kasturi, gaul perlahan.", "Jika terlalu masin/masam, tambah secubit gula.", "Siap! Hidang bersama ulam & asam pedas."]'::jsonb,
    NULL,
    '["sides", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Ikan Bakar Sambal Portugis (ID: 284)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    284,
    'Ikan Bakar Sambal Portugis',
    'Sides',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "secukupnya", "unit": "", "name": "Bahan: Ikan pilihan secukupnya (siakap / pari / kembung/bawal /ikan cencaru) Air asam jawa secukupnya minyak masak secukupnya"}, {"amount": "6-10", "unit": "biji", "name": "bendi"}, {"amount": "2", "unit": "helai", "name": "daun limau purut (carikkan) Garam secukup rasa Gula secukup rasa (boleh guna gula melaka) Daun pisang (Jika ada)"}, {"name": "\u2014 Bahan Kisar \u2014", "amount": "", "unit": ""}, {"amount": "3", "unit": "biji", "name": "bawang merah besar"}, {"amount": "4", "unit": "ulas", "name": "bawang putih"}, {"amount": "2", "unit": "batang", "name": "serai"}, {"amount": "3", "unit": "biji", "name": "buah keras"}, {"amount": "5-10", "unit": "", "name": "tangkai Cili kering (rendam/rebus sehingga lembut)"}]'::jsonb,
    '["Kisar semua bahan kisar hingga halus.", "Panaskan minyak secukupnya dalam kuali.", "Tumis bahan kisar hingga naik bau dan pecah minyak. Tumis hingga betul-betul masak (warna merah cantik).", "Masukkan daun limau purut.", "Perasakan dengan garam, gula dan air asam jawa. Sesuaikan rasa.", "Sambal tak perlu terlalu kering, biar sedikit berkuah. Tutup api.", "Jika guna ikan yang sedikit pejal, boleh masukkan ikan ke dalam sambal seketika. Anggaran 2-3minit. IKAN BAKAR SAMBAL PORTUGIS", "Setelah sambal siap dimasak, ambil daun pisang dan layurkan seketika.", "Letakkan sedikit sambal di atas daun pisang.", "Susun ikan di atas sambal.", "Tutup ikan dengan sedikit sambal lagi.", "Masukkan bendi sekali di sisi ikan. Bendi dipotong serong.", "Balut kemas ikan bersama sambal menggunakan daun pisang.", "Bakar di atas kuali leper / kuali grill dengan api sederhana hingga daun pisang hangus sedikit dan aroma naik. Anggaran 7-10minit setiap bahagian. Balikkan bungkusan sekali supaya masak sekata.", "Boleh tutup kuali untul hasil bakar yang lebih sekata."]'::jsonb,
    '["Bakar dengan api sederhana supaya daun pisang tak terbakar cepat.", "Pastikan daging ikan mudah dicucuk garpu dan warna bertukar ke perang keemasan."]'::jsonb,
    '["sides", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Sotong Bakar Portugis Style (ID: 285)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    285,
    'Sotong Bakar Portugis Style',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[]'::jsonb,
    '["Bersihkan sotong, buang tulang plastik.", "Jangan potong kecil biar seketul / kelar", "Gaul sotong dengan sedikit garam dan perahan limau nipis.", "Bilas cepat & toskan (hilangkan hanyir).", "Ambil daun pisang, letak sedikit sambal Portugis.", "Letak sotong, tutup dengan sambal lagi.", "Boleh tambah bendi / bawang besar (optional).", "Balut kemas daun pisang.", "Bakar atas kuali leper api sederhana. 3\u20135 minit setiap sisi sahaja.", "Jangan bakar lama sotong akan liat."]'::jsonb,
    '["Bakar cepat dengan api sederhana", "Sotong dah masak bila badan dia mengecut & bertukar putih legap"]'::jsonb,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Air Asam Kicap Sempoi (ID: 286)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    286,
    'Air Asam Kicap Sempoi',
    'Sides',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "10", "unit": "biji - ikut tahap pedas, dihiris halus) Kicap Manis  Limau kasturi (3-5 biji perah jusnya)", "name": "Bahan: Bawang merah (3 biji, dihiris halus) Cili padi merah & hijau (5 (secukup rasa, biasanya 2-3 sudu besar)"}]'::jsonb,
    '["Masukkan bawang merah & cili padi dalam mangkuk.", "Perah jus limau kasturi ke atas bawang dan cili.", "Tambahkan kicap manis secukupnya.", "Gaul rata dan biarkan 5\u201310 minit supaya rasa meresap.", "Rasa sebelum hidang, jika perlu letak garam boleh tambah sedikit.", "Hidangkan sebagai sambal pencicah atau pencicah ikan bakar."]'::jsonb,
    NULL,
    '["sides", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Nasi Ayam 1 Periuk (Ala Thai) (ID: 287)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    287,
    'Nasi Ayam 1 Periuk (Ala Thai)',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan Tumis \u2014", "amount": "", "unit": ""}, {"amount": "secukupnya", "unit": "", "name": "1 inci halia (hiris nipis)"}, {"amount": "secukupnya", "unit": "", "name": "3 ulas bawang putih (diketuk)"}, {"amount": "secukupnya", "unit": "", "name": "\u00bc biji bawang Holland / bawang merah besar (hiris kasar)"}, {"amount": "secukupnya", "unit": "", "name": "1 helai daun pandan (simpul)"}, {"amount": "secukupnya", "unit": "", "name": "1 pokok daun ketumbar (ambil akar)"}, {"amount": "3", "unit": "sudu besar", "name": "minyak masak"}, {"amount": "1", "unit": "sudu besar", "name": "mentega / lemak ayam"}, {"amount": "secukupnya", "unit": "", "name": "2 ketul whole leg ayam (\u00b1\u00bd ekor) (kelar sedikit)"}, {"amount": "5", "unit": "cawan", "name": "air"}, {"amount": "1", "unit": "kiub", "name": "pati ayam Garam secukup rasa Serbuk lada sulah (optional)"}, {"name": "\u2014 Bahan Nasi \u2014", "amount": "", "unit": ""}, {"amount": "secukupnya", "unit": "", "name": "2 cawan beras basmathi (basuh, rendam 15 min & tos)"}, {"amount": "3", "unit": "cawan", "name": "air rebusan ayam Ayam rebus (dari sup tadi) Akar ketumbar (optional)"}]'::jsonb,
    '["Panaskan periuk masukkan minyak & mentega.", "Tumis bawang putih, bawang Holland & halia hingga wangi.", "Masukkan daun pandan & akar ketumbar. Tumis seketika.", "Masukkan ayam, gaul sampai ayam kecut sedikit.", "Tuang 5 cawan air dan masukkan kiub pati ayam.", "Reneh perlahan anggaran \u00b120\u201325 min hingga ayam masak & air jadi stok sedap.", "Keluarkan ayam, asingkan 3 cawan air rebusan untuk masak nasi.", "Simpan lebihan sup untuk dihidang bersama nasi.", "Dalam periuk yang sama, masukkan beras basmathi dan 3 cawan air rebusan ayam.", "Kacau supaya beras dan sup sebati.", "Bila beras hampir mendidih, susun ayam di atas nasi, tabur sedikit lada sulah.", "Masak seperti biasa/rice cooker. Set api perlahan hingga nasi masak."]'::jsonb,
    '["Ayam boleh di goreng/bakar sedikit untuk warna yang lebih cantik.", "Boleh guna beras biasa atau beras wangi. Adjust air untuk masak nasi seperti masak nasi biasa.", "Boleh perah limau nipis dalam sup sebelum dihidang untuk rasa yang lebih segar.", "Bahan Hiasan & Hidangan: Timun hiris Tomato hiris Daun salad"]'::jsonb,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Sos Special Nasi Ayam Ala Thai (ID: 288)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    288,
    'Sos Special Nasi Ayam Ala Thai',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "5", "unit": "ulas", "name": "bawang putih"}, {"amount": "5-10", "unit": "", "name": "cili padi (ikut tahap kepedasan)"}, {"amount": "5", "unit": "", "name": "cili merah besar Segenggam daun ketumbar"}, {"amount": "2", "unit": "sudu besar", "name": "gula perang/palm sugar"}, {"amount": "3", "unit": "sudu besar", "name": "sos ikan Thai Jus limau nipis (ikut masam disukai)"}, {"amount": "3", "unit": "sudu besar", "name": "sos cili Thai"}]'::jsonb,
    '["Kisar kasar semua bahan kecuali jus Limau.", "Masukkan perahan limau, rasa dan seimbangkan rasa masam, manis, masin & pedas.", "Simpan dalam chiller seketika untuk rasa yang lebih sedap."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Lemon Loaf CWC (ID: 289)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    289,
    'Lemon Loaf CWC',
    'Desserts',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan Kek \u2014", "amount": "", "unit": ""}, {"amount": "1\u00be", "unit": "cawan", "name": "(210g) tepung gandum"}, {"amount": "2", "unit": "sudu besar", "name": "(14g) tepung jagung"}, {"amount": "1\u00bd", "unit": "sudu kecil", "name": "baking powder"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "garam (abaikan jika guna mentega masin)"}, {"amount": "secukupnya", "unit": "", "name": "\u00bd cawan (120g) susu segar penuh krim (suam)"}, {"amount": "3", "unit": "sudu besar", "name": "(42g) jus lemon segar"}, {"amount": "secukupnya", "unit": "", "name": "\u00be cawan (170g) mentega tanpa garam (suhu bilik)"}, {"amount": "2", "unit": "sudu besar", "name": "(26g) minyak sayuran (contoh: canola)"}, {"amount": "1", "unit": "cawan", "name": "(200g) gula pasir"}, {"amount": "1\u00bd", "unit": "sudu besar", "name": "parutan kulit lemon"}, {"amount": "secukupnya", "unit": "", "name": "3 biji telur saiz besar A/B (suhu bilik)"}]'::jsonb,
    '["Panaskan oven pada suhu 160\u00b0C (off kipas). Alas loyang loaf saiz 8.5 x 4.5 inci dengan baking paper.", "Ayak & gaul kering: Tepung gandum, tepung jagung, baking powder dan garam. Ketepikan.", "Campur susu & lemon: Gaul susu suam dengan jus lemon. Biarkan \u2013 ia akan berketul (normal).", "Pukul mentega: Mentega, minyak, gula dan kulit lemon dipukul \u00b12 minit hingga gebu dan pucat.", "Masukkan telur satu persatu, pukul hingga sebati setiap kali.", "Masuk bahan cecair & kering secara berselang:", "Masukkan \u00bd campuran susu lemon, gaul", "Masukkan \u00bd bahan kering, kaup balik", "Masukkan baki susu lemon, kaup balik", "Akhir sekali baki bahan kering, kaup balik perlahan. Jangan overmix. LEMON LOAF CWC", "Tuang adunan ke dalam loyang, ratakan. Hentak loyang 3 kali.", "Bakar 50-60 minit atau hingga cucuk lidi keluar bersih. Sejukkan dalam loyang 10 minit, kemudian keluarkan kek.", "Bahan Special Lemon syrup:", "\u00bc cawan (50g) gula pasir", "\u00bc cawan (55g) jus lemon segar", "Masak gula dan jus lemon atas api sederhana hingga gula larut.", "Siram keseluruhan kek (termasuk bahagian bawah) ketika kek masih suam.", "Biarkan kek sejuk sepenuhnya.", "Bahan Lemon Glaze:", "1 cawan (125g) gula aising", "1\u00bd sudu besar (20g) jus lemon", "1 sudu besar parutan kulit lemon (hiasan \u2013 optional)", "Campur gula aising dan jus lemon hingga pekat berkilat.", "Sapu di atas kek yang telah sejuk.", "Tabur parutan kulit lemon (optional)."]'::jsonb,
    NULL,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Shrimp Garlic Homemade Pasta (ID: 290)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    290,
    'Shrimp Garlic Homemade Pasta',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan: 250g Homemade Pasta Beku/ Pasta Beli Siap \u2014", "amount": "", "unit": ""}, {"amount": "secukupnya", "unit": "", "name": "400g udang (15pcs) (buang kulit & urat Serbuk lada hitam secukup rasa Serbuk paprika secukup rasa Minyak zaitun 30g mentega)"}, {"amount": "secukupnya", "unit": "", "name": "7 ulas bawang putih (dicincang halus)"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "chili flakes (ikut tahap pedas)"}, {"amount": "secukupnya", "unit": "", "name": "150 g tomato ceri (dibelah dua Air rebusan pasta secukupnya)"}, {"amount": "secukupnya", "unit": "", "name": "Daun parsley segar (dicincang)"}]'::jsonb,
    '["Rebus Homemade Frozen Pasta", "Didihkan air yang banyak + garam", "Masukkan pasta terus dari freezer (tak perlu nyahbeku)", "Rebus selama 2\u20133 minit atau hingga pasta timbul & lembut (jika halus)", "Rebus selama 4\u20135 minit atau hingga pasta timbul & lembut (jika tebal)", "Angkat dan simpan air rebusan pasta \u26a0 Jangan rebus terlalu lama, nanti pasta jadi lembik", "*Jika guna pasta yang beli siap, boleh rujuk masa rebus pasta pada bungkusan. Buat seperti biasa. SHRIMP GARLIC HOMEMADE PASTA", "Masak Udang", "Perasakan udang dengan lada hitam dan paprika. Biarkan seketika.", "Panaskan minyak zaitun + mentega dalam kuali", "Goreng udang 1\u20132 minit setiap sisi hingga bertukar warna", "Angkat dan ketepikan", "Buat Sos dan satukan semua bahan", "Dalam kuali yang sama, masukkan bawang putih & chili flakes", "Tumis dengan api sederhana hingga naik bau (jangan hangus)", "Masukkan tomato, masak hingga lembut", "Hancurkan tomato sedikit guna sudip.", "Masukkan sedikit air rebusan pasta", "Masukkan semula udang", "Masukkan pasta dan gaul hingga sos bersalut cantik", "Tambah lagi pasta water jika perlu.", "Tabur parsley segar. Perasakan jika perlu dan terus hidang", "Pasta timbul ke permukaan air", "Tekstur lembut tapi masih ada bite (al dente)", "Bahagian tengah tak lagi keras / putih"]'::jsonb,
    '["Cara confirm homemada pasta dah masak sempurna"]'::jsonb,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Bubur Kacang Hijau Bersama Durian (ID: 291)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    291,
    'Bubur Kacang Hijau Bersama Durian',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan: 200gm Kacang Hijau \u2014", "amount": "", "unit": ""}, {"amount": "500", "unit": "ml", "name": "santan 150gm gula merah/gula melaka. 150gm gula pasir"}, {"amount": "\u00bc", "unit": "sudu kecil", "name": "garam"}, {"amount": "2", "unit": "helai", "name": "daun pandan (disimpul) Air tambahan jika perlu Durian ikut kesesuaian (optional)"}]'::jsonb,
    '["Rendam kacang hijau 30 minit sahaja. Toskan air.", "Sangai kacang yang telah direndam sehingga wangi (tidak terlalu lama, sekadar naik aroma dan warna kacang sedikit coklat.", "Rebus kacang hijau dengan air secukupnya. Api sederhana. Tutup periuk supaya wap bantu kacang cepat empuk", "Anggaran masa Merebus 20\u201330minit kalau kacang telah direndam 30 minit. Kacau sekali-sekala supaya kacang tak melekat. Tambah air panas jika air surut sebelum kacang empuk.", "Bila kacang sudah empuk, masukkan, daun pandan, gula merah & gula pasir. Kacau hingga gula larut sepenuhnya.", "Tuang santan sedikit demi sedikit sambil kacau perlahan dengan api sederhana kecil supaya santan tidak pecah.", "Perasakan dengan garam secukupnya.", "Masukkan isi durian ikut selera. Masak sekejap sahaja hingga aroma naik.", "Tutup api dan sedia dihidang."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Roti Paung Express (ID: 292)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    292,
    'Roti Paung Express',
    'Breakfast',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "325", "unit": "g", "name": "tepung gandum (\u2248 2 1/2 cups, tidak padat)"}, {"amount": "150", "unit": "ml", "name": "susu segar suam (not hot) (\u2248 1/2 cup + 2 sudu besar)"}, {"amount": "1", "unit": "biji", "name": "telur"}, {"amount": "50", "unit": "g", "name": "butter (\u2248 3 1/2 sudu besar)"}, {"amount": "6", "unit": "g", "name": "yis (instant/active dried yeast) (\u2248 2 sudu kecil)"}, {"amount": "30", "unit": "g", "name": "gula (\u2248 2 1/2 sudu besar)"}, {"amount": "6", "unit": "g", "name": "garam (\u2248 1 sudu kecil)"}, {"name": "\u2014 Untuk Sapuan (egg Wash, Optional) \u2014", "amount": "", "unit": ""}, {"amount": "1", "unit": "biji", "name": "telur (dipukul sedikit)"}]'::jsonb,
    '["Dalam mangkuk besar, masukkan susu suam, gula, yis, telur, garam, butter, dan tepung.", "Gaul hingga menjadi doh kasar.", "Alihkan doh ke permukaan kerja bersih, uli doh sehingga lembut dan elastik. Anggaran 10-15minit.", "Doh yang cukup uli akan boleh diregang menjadi membran nipis tanpa koyak (windowpane test).", "Doh masih sticky sedikit, tapi permukaan licin. ROTI PAUNG EXPRESS", "Bahagikan doh kepada 13 bahagian sama berat (~47g setiap satu).", "Bentuk setiap bahagian menjadi bulatan kecil, lipat tepi doh ke tengah supaya bahagian atas licin.", "Susun doh di atas loyang yang telah disapu mentega atau dialas parchment paper. Abid guna loyang bulat 9inci. C. Proof Doh (Fermentasi Cepat = OVEN STEAMING)", "Tutup loyang dengan cling film atau kain lembap.", "Letakkan loyang di dalam oven yang hangat, bukan panas:", "Hidupkan oven pada suhu paling rendah (contoh: 50\u00b0C / 120\u00b0F).", "Setelah oven panas, tutup dan matikan oven, buka sedikit pintu dan masukkan loyang.", "Suhu dalam oven kini sekitar 30\u00b0C / 85\u00b0F \u2013 sesuai untuk proofing.", "Biarkan doh naik selama 25 minit.", "Doh akan naik dengan cantik, gebu dan lembut. D. Panaskan Oven dan Sapuan Telur", "Panaskan oven ke 180\u00b0C / 350\u00b0F. Selama 10minit.", "Sebelum bakar, sapukan egg wash pada permukaan doh untuk hasil keemasan. ROTI PAUNG EXPRESS", "Bakar 20\u201322 minit pada 180\u00b0C / 350\u00b0F. Rak tengah. Off kipas set api atas bawah. Biasanya pada masa ke 17 minit, atas doh mula keperangan \u2013 jangan anggap dah siap. Pastikan bakar sampai matang sepenuhnya.", "Setelah keluar dari oven, sapu mentega cair pada atas rolls untuk lebih lembut dan wangi.", "Alih ke cooling rack dan hidang hangat."]'::jsonb,
    '["Pasang hook / dough hook pada mixer.", "Masukkan semua bahan doh kecuali butter, kacau dulu 1\u20132 minit sampai", "bahan sebati.", "Masukkan butter (lembut atau cair) sedikit demi sedikit.", "Uli doh dengan speed sederhana (medium)", "\u201310 minit untuk mixer biasa (stand mixer rumah)", "Doh harus lembut, elastik, dan buat windowpane test: boleh regangkan tanpa koyak.", "Jangan lebih 12 minit, nanti doh terlalu liat.", "Kalau doh masih melekat, tabur sedikit tepung (1\u20132 tsp) sahaja.", "Selepas uli mixer, boleh terus ke langkah proofing", "minit."]'::jsonb,
    '["breakfast", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Pindang Serani Paling Mudah (ID: 293)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    293,
    'Pindang Serani Paling Mudah',
    'Mains',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "secukupnya", "unit": "", "name": "1 ekor ikan tenggiri (dipotong sederhana)"}, {"amount": "secukupnya", "unit": "", "name": "2 biji bawang merah besar (dihiris)"}, {"amount": "secukupnya", "unit": "", "name": "3 ulas bawang putih (dihiris)"}, {"amount": "secukupnya", "unit": "", "name": "1 inci halia (dihiris halus)"}, {"amount": "secukupnya", "unit": "", "name": "2 batang serai (diketuk)"}, {"amount": "secukupnya", "unit": "", "name": "1 biji tomato (dibelah 4)"}, {"amount": "secukupnya", "unit": "", "name": "2 biji cili merah (dibelah)"}, {"amount": "secukupnya", "unit": "", "name": "2 biji cili hijau (dibelah)"}, {"amount": "1-2", "unit": "sudu kecil", "name": "serbuk kunyit (ikut citarasa)"}, {"amount": "2-3", "unit": "keping", "name": "asam gelugur (secukupnya) Garam secukup rasa Gula sedikit"}, {"amount": "4", "unit": "cawan", "name": "air (secukupnya) Minyak sedikit untuk menumis"}]'::jsonb,
    '["Panaskan sedikit minyak dalam periuk.", "Tumis bawang merah, bawang putih dan halia hingga naik bau dan sedikit layu (tak perlu garing).", "Masukkan serai dan serbuk kunyit, kacau sekejap.", "Tuang 3\u20134 cawan air, biarkan mendidih.", "Perasakan dengan garam dan sedikit gula (imbang masam & manis).", "Masukkan asam gelugur. Apabila kuah mendidih, masukkan ikan tenggiri.", "Masukkan cili merah, cili hijau dan tomato.", "Masak dengan api sederhana perlahan anggaran \u00b18\u201310 minit sahaja, jangan kacau terlalu kerap supaya ikan tak hancur.", "Tutup api bila ikan masak dan kuah rasa seimbang. Siap."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Express Pizza (ID: 294)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    294,
    'Express Pizza',
    'Breakfast',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "secukupnya", "unit": "", "name": "Bahan: 140g Self (Rising Flour  140g Yogurt plain ( \u00bd cawan lebih sikit) Topping Pilihan Sos Pilihan)"}, {"amount": "secukupnya", "unit": "", "name": "Jika tiada yogurt: 85g susu (\u00b1 \u2153 cawan)"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "cuka ATAU jus lemon (Campur & biarkan 5 minit sebelum guna)"}, {"amount": "secukupnya", "unit": "", "name": "Cara Buat Self (Rising Flour Sendiri Pilihan 1)"}, {"amount": "140", "unit": "g", "name": "tepung gandum (\u00b1 1 cawan)"}, {"amount": "1\u00bd", "unit": "sudu kecil", "name": "baking powder Pilihan 2 (Guna Baking Soda)"}, {"amount": "140", "unit": "g", "name": "tepung gandum (\u00b1 1 cawan)"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "baking soda"}]'::jsonb,
    '["Dalam mangkuk besar, gaulkan self-raising flour dan yogurt sehingga menjadi doh.", "Pindahkan doh ke permukaan yang ditabur tepung. Uli sekejap sehingga doh lembut dan tidak melekat. Tambah tepung sikit-sikit sahaja.", "Bahagikan doh kepada 2 bahagian sama besar. Rehatkan selama beberapa minit (\u00b15 minit) EXPRESS PIZZA", "Canai doh mengikut saiz kuali yang akan digunakan. Boleh tabur tepung sikit-sikit.", "Panaskan Kuali. Gris kuali dengan sedikit minyak. Letakkan doh dan masak sebelah bahagian dengan api kecil. Anggaran 4\u20135 minit. Ikut ketebalan. Jika doh nipis mungkin lebih cepat.", "Kemudian, terbalik doh. Sapukan sos ikut citarasa kemudian tambah topping pilihan.", "Tutup kuali dengan penutup. Masak beberapa minit lagi sehingga keju cair dan doh masak sepenuhnya. Anggaran 5-6 minit sehingga keju cair & doh masak sepenuhnya"]'::jsonb,
    '["Bahagian bawah perang keemasan", "Doh bila ditekan naik semula", "Keju cair sepenuhnya", "Tiada bau tepung mentah"]'::jsonb,
    '["breakfast", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Nasi Beringin Cara CWC (ID: 295)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    295,
    'Nasi Beringin Cara CWC',
    'Mains',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "secukupnya", "unit": "", "name": "NASI BERINGIN CARA CWC Page 1"}, {"name": "\u2014 Bahan Utama \u2014", "amount": "", "unit": ""}, {"amount": "4", "unit": "cawan", "name": "beras basmathi"}, {"amount": "secukupnya", "unit": "", "name": "1 biji bawang besar (dimayang)"}, {"amount": "secukupnya", "unit": "", "name": "1 inci halia (dihiris)"}, {"amount": "secukupnya", "unit": "", "name": "2 helai daun pandan (disimpul)"}, {"amount": "secukupnya", "unit": "", "name": "2 batang serai (diketuk)"}, {"amount": "4", "unit": "", "name": "sekawan (1 batang kayu manis, 2 kuntum bunga lawang, 3 biji buah pelaga, 4 biji bunga cengkih)"}, {"amount": "1\u00bd", "unit": "sudu makan", "name": "minyak sapi"}, {"amount": "1\u00bd", "unit": "sudu makan", "name": "minyak masak"}, {"name": "\u2014 Bahan Kisar \u2014", "amount": "", "unit": ""}, {"amount": "\u00bd", "unit": "biji", "name": "bawang besar"}, {"amount": "3", "unit": "ulas", "name": "bawang putih"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "jintan putih"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "jintan manis"}, {"amount": "1\u00bc", "unit": "sudu kecil garam", "name": "Cecair & perasa: 1 (secukup rasa)"}, {"amount": "5", "unit": "cawan", "name": "air"}, {"amount": "1", "unit": "cawan", "name": "santan Nisbah: 1 cawan beras basmati : 1\u00bd cawan cecair"}]'::jsonb,
    '["Basuh & rendam beras 20 minit, toskan.", "Tumis 4 sekawan, pandan & serai dengan minyak sapi + minyak.", "Masukkan bawang & halia, tumis wangi.", "Masukkan bahan kisar, tumis hingga pecah minyak.", "Masukkan beras, gaul 2 minit.", "Masukkan 1 cawan santan + 5 cawan air dan garam. Kacau dan rasa.", "Masak seperti biasa atas dapur atau dalam periuk nasi sehingga nasi masak & berderai."]'::jsonb,
    '["Air mesti sedikit masin sebelum masak nasi.", "Jangan kacau selepas nasi mula mendidih", "Lepas masak, biar 10 minit baru gembur."]'::jsonb,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Ayam Ros Paling Mudah (ID: 296)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    296,
    'Ayam Ros Paling Mudah',
    'Mains',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "secukupnya", "unit": "", "name": "1 ekor ayam (potong, cuci bersih, gaul garam & kunyit, goreng separuh masak)"}, {"amount": "6", "unit": "sudu besar", "name": "Serbuk Kari"}, {"amount": "\u00bd -1", "unit": "cawan", "name": "susu cair/santan Garam & gula secukup rasa"}, {"name": "\u2014 Bahan Kisar \u2014", "amount": "", "unit": ""}, {"amount": "8", "unit": "biji", "name": "bawang merah/ 4 biji bawang besar"}, {"amount": "5", "unit": "ulas", "name": "bawang putih"}, {"amount": "2", "unit": "", "name": "inci halia"}, {"amount": "2", "unit": "biji", "name": "tomato"}, {"amount": "5", "unit": "", "name": "tangkai cili kering (adjust ikut tahap kepedasan)"}, {"name": "\u2014 Bahan Tumis \u2014", "amount": "", "unit": ""}, {"amount": "1", "unit": "cawan", "name": "minyak lebihan goreng ayam"}, {"amount": "secukupnya", "unit": "", "name": "2 biji bawang besar (hiris nipis)"}, {"amount": "secukupnya", "unit": "", "name": "5 ulas bawang putih (hiris)"}, {"amount": "2", "unit": "helai", "name": "daun pandan Rempah 4 sekawan (1 batang kayu manis, 4 bunga cengkih, 3 bunga lawang, 4 buah pelaga) AYAM ROS PALING MUDAH"}]'::jsonb,
    '["Goreng ayam separuh masak dalam kuali dengan minyak panas. Angkat & tos.", "Tumis bahan. Guna minyak lebihan goreng ayam.", "Tumis rempah 4 sekawan & daun pandan hingga wangi", "Masukkan bawang besar & bawang putih hiris, tumis hingga keperangan,", "Masukkan bahan kisar, tumis hingga pecah minyak & naik aroma wangi.", "Masukkan serbuk kari masak merah, tumis hingga kuah cantik merah & berbau harum.", "Masukkan ayam, gaul rata hingga ayam bersalut kuah.", "Tuang susu cair atau santan, perasakan dengan garam & gula secukup rasa. Guna gula melaka untuk rasa yang lebih padu.", "Reneh api perlahan selama 8\u201310 minit sehingga kuah pekat & sebati dengan ayam. Boleh tutup kuali jika nak hasil yang lebih pekat.", "Tutup api & biarkan kuah \u201cresting\u201d sekejap sebelum dihidang agar rasa lebih mesra."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Kuih Siput Klasik (ID: 297)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    297,
    'Kuih Siput Klasik',
    'Snacks',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "4", "unit": "cawan", "name": "tepung gandum (500gm)"}, {"amount": "\u00bd", "unit": "cawan", "name": "marjerin (120gm)"}, {"amount": "1", "unit": "sudu kecil", "name": "garam"}, {"amount": "1", "unit": "sudu besar", "name": "jintan manis (disangai & ditumbuk)"}, {"amount": "1", "unit": "sudu besar", "name": "biji ketumbar (disangai & ditumbuk)"}, {"name": "\u2014 Bahan Kisar Halus \u2014", "amount": "", "unit": ""}, {"amount": "1", "unit": "biji", "name": "telur (gred A/B/C)"}, {"amount": "2", "unit": "sudu besar", "name": "udang kering ( rendam)"}, {"amount": "1", "unit": "sudu besar", "name": "rempah kari daging"}, {"amount": "\u00bd", "unit": "sudu besar", "name": "serbuk cili"}, {"amount": "4", "unit": "biji", "name": "bawang merah (dikisar)"}, {"amount": "\u00bc", "unit": "cawan", "name": "santan"}, {"amount": "\u00bc", "unit": "cawan", "name": "air"}, {"name": "\u2014 Bahan Sangai. \u2014", "amount": "", "unit": ""}, {"amount": "secukupnya", "unit": "", "name": "Lain (lain: Air sejuk untuk uli doh  Daun kari jika suka Minyak untuk menggoreng Acuan kuih siput KUIH SIPUT KLASIK)"}]'::jsonb,
    '["Sangai jintan manis dan biji ketumbar hingga wangi. Tumbuk atau kisar kasar, Ketepikan.", "Dalam pengisar masukkan bahan kisar. Kisar sehingga halus.", "Dalam mangkuk besar, masukkan tepung gandum dan garam. Gaul sehingga sebati.", "Kemudian, masukkan marjerin. Gaul ramas sehingga menjadi seperti serbuk roti.", "Seterusnya, masukkan bahan kisar tadi. Kacau perlahan sehingga semua", "bahan sebati dengan spatula atau sudu.", "Kemudian, masukkan air sejuk sedikit demi sedikit sambil menguli doh. Jangan masuk air sekali gus.", "Uli sehingga doh sebati. Doh perlu lembut dan tidak melekat ditangan.", "Rehatkan doh seketika. Anggaran 10minit.", "Griskan dulang atau tray dengan sedikit minyak.", "Kemudian boleh membentuk kuih siput dengan acuan pilihan.", "Cubit doh kecil sahaja. Kemudian tekan dan gulung nipis panjang atas papan kuih siput atau belakang garpu. Letakkan di atas dulang yang telah digriskan minyak awal tadi. Buat sehingga doh siput habis.", "Panaskan minyak secukupnya dan set api sederhana. Guna kaedah goreng deep fry.", "Goreng kuih siput sambil kacau supaya kuih tidak melekat. Boleh masukkan daun kari untuk naikkan rasa dan bau.", "Goreng hingga keemasan & rangup. Buih akan berkurangan. Jangan terlalu gelap, nanti pahit.", "Angkat dan toskan kuih. Sejukkan sepenuhnya. Simpan dalam bekas kedap udara."]'::jsonb,
    NULL,
    '["snacks", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Sambal Telur Hancur CWC (ID: 298)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    298,
    'Sambal Telur Hancur CWC',
    'Sides',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "2", "unit": "biji", "name": "bawang besar"}, {"amount": "5", "unit": "ulas", "name": "bawang putih"}, {"name": "\u2014 Bahan Lain 1\u20132 Biji Bawang Besar (potong Bulat) \u2014", "amount": "", "unit": ""}, {"amount": "6", "unit": "biji", "name": "telur"}, {"amount": "2", "unit": "sudu kecil garam  Air asam jawa secukupnya Minyak masak secukupnya", "name": "1 sudu besar gula ( secukup rasa) 1 (secukup rasa)"}]'::jsonb,
    '["Panaskan minyak dalam kuali. Tumiskan bahan kisar sehingga naik bau.", "Masak sambal hingga garing dan pecah minyak. Tambah sedikit air (2 kali) supaya sambal masak cantik.", "Bila sambal betul-betul pecah minyak, masukkan sedikit air asam jawa. Gaul rata.", "Masukkan gula dan garam. Gaul dan rasa \u2013 sambal perlu ada pedas, manis dan sedikit masam.", "Pecahkan telur satu persatu. Biarkan telur set sedikit.", "Kacau hingga telur hancur dan bersalut sambal.", "Masukkan bawang besar potong bulat, gaul rata dan masak 2\u20133 minit hingga layu.", "Tutup api dan sedia dihidang. Tip Hidangan: Hidang panas-panas bersama nasi putih dan kicap \u2013 ringkas tapi padu!"]'::jsonb,
    NULL,
    '["sides", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Mee Hailam Sempoi (ID: 299)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    299,
    'Mee Hailam Sempoi',
    'Mains',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan Untuk Mee (dicelur) Air Secukupnya \u2014", "amount": "", "unit": ""}, {"amount": "1", "unit": "", "name": "pek / 450 g mee kuning"}, {"name": "\u2014 Bahan: Sedikit Minyak (untuk Menumis) \u2014", "amount": "", "unit": ""}, {"amount": "2", "unit": "ulas", "name": "bawang putih (cincang)"}, {"amount": "1", "unit": "biji", "name": "bawang merah kecil (hiris)"}, {"amount": "1-2", "unit": "sudu besar", "name": "cili kisar (ikut citarasa)"}, {"amount": "1", "unit": "", "name": "ketul dada ayam (hiris kecil)"}, {"amount": "6", "unit": "", "name": "ekor udang besar (buang kulit)"}, {"amount": "1", "unit": "", "name": "ekor sotong (bersihkan & potong)"}, {"amount": "1", "unit": "sudu kecil", "name": "lada sulah"}, {"amount": "\u00bd", "unit": "batang", "name": "karot (hiris nipis)"}, {"amount": "secukupnya", "unit": "", "name": "2 batang baby corn (hiris serong (jika suka) sayur sawi secukupnya)"}, {"amount": "3-4", "unit": "cawan", "name": "air (anggaran)"}, {"amount": "3", "unit": "sudu besar", "name": "sos tomato"}, {"amount": "3", "unit": "sudu besar", "name": "sos cili"}, {"amount": "1", "unit": "sudu besar", "name": "sos tiram Kicap manis secukupnya (hingga warna kuah gelap)"}, {"amount": "1", "unit": "biji", "name": "tomato (belah 4) Garam secukup rasa"}, {"amount": "1", "unit": "sudu kecil", "name": "tepung jagung + sedikit air (bancuh) MEE HAILAM SEMPOI"}]'::jsonb,
    '["Celur mee", "Didihkan air, celur mee kuning seketika. 30saat-1minit sahaja.", "Toskan dan ketepikan.", "Tumis bahan asas", "Panaskan minyak.", "Tumis bawang putih & bawang merah hingga wangi.", "Masukkan cili kisar, tumis hingga pecah minyak.", "Masukkan protein", "Masukkan isi ayam, kacau hingga ayam masak.", "Masukkan separuh lada sulah & garam secukup rasa.", "Masukkan sayur & kuah", "Masukkan karot, batang sawi & baby corn jika ada", "Tuang air, masukkan sos tomato, sos cili & sos tiram.", "Masukkan kicap manis sedikit demi sedikit. Didihkan seketika.", "Perasakan", "Masukkan udang & sotong, masak seketika.", "Masukkan tomato dan daun sawi. MEE HAILAM SEMPOI", "Pekatkan kuah", "Masukkan bancuhan tepung jagung sedikit demi sedikit.", "Kacau hingga kuah likat & mendidih.", "Akhir sekali", "Masukkan baki lada sulah (kali ke-2).", "Tutup api.", "Letakkan mee dalam pinggan.", "Curahkan kuah Mee Hailam panas.", "Tabur bahan hiasan dan perah limau nipis. Tip sedap : tambah sedikit minyak bijan di hujung masakan untuk aroma ala kedai Cina Muslim."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Easy Churros (ID: 300)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    300,
    'Easy Churros',
    'Desserts',
    'Intermediate',
    '45 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "1", "unit": "cawan", "name": "air (240 ml)"}, {"amount": "6", "unit": "sudu besar", "name": "mentega tanpa garam (85 g)"}, {"amount": "1", "unit": "sudu besar", "name": "gula"}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "garam"}, {"amount": "secukupnya", "unit": "", "name": "1 cawan tepung gandum / all (purpose flour)"}, {"amount": "3", "unit": "biji", "name": "telur besar (A/B) Sediakan extra telur."}, {"amount": "1", "unit": "sudu kecil", "name": "esen vanilla Minyak masak secukupnya (untuk menggoreng) Cinnamon Sugar (Salutan)"}, {"amount": "\u00be", "unit": "cawan", "name": "gula halus"}, {"amount": "2", "unit": "sudu kecil", "name": "serbuk kayu manis"}]'::jsonb,
    '["Dalam periuk, masukkan air, mentega, gula dan garam. Masak hingga mendidih kuat, kemudian tutup api.", "Masukkan tepung sekaligus, kacau laju dengan senduk kayu hingga jadi doh (30\u201360 saat).", "Hidupkan api semula dan masak sambil kacau selama 30 saat untuk keringkan doh.", "Pindahkan doh ke dalam mangkuk mixer (guna paddle atau hand mixer).", "Pukul pada kelajuan sederhana. Masukkan telur satu persatu, diikuti vanilla. Doh siap bila licin, berkilat & jatuh perlahan (V Shape) dari spatula.", "Panaskan minyak pada suhu 170\u2013180\u00b0C (370\u00b0F). EASY CHURROS", "Masukkan doh ke dalam piping bag dengan mata bintang besar (869 atau closed star).", "Paip churros sepanjang \u00b14-6 inci terus ke dalam minyak (goreng 2\u20133 batang sahaja sekali).", "Goreng 90 saat \u2013 2 minit setiap sisi hingga keemasan.", "Angkat, toskan sekejap, kemudian gaul terus dengan cinnamon sugar semasa panas. Chocolate Dipping Sauce \u2154 cawan chocolate chips \u2154 cawan whipping cream / heavy cream"]'::jsonb,
    NULL,
    '["desserts", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Daging Goreng Kunyit Simple (ID: 301)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    301,
    'Daging Goreng Kunyit Simple',
    'Mains',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"name": "\u2014 Bahan: 500g Daging Lembu (potong Nipis) \u2014", "amount": "", "unit": ""}, {"amount": "\u00bd", "unit": "sudu kecil", "name": "baking soda Air secukupnya (untuk perapan & rebus) Sedikit garam"}, {"amount": "\u00bc", "unit": "cawan", "name": "minyak masak"}, {"amount": "2", "unit": "sudu kecil", "name": "serbuk kunyit"}, {"amount": "4", "unit": "ulas", "name": "bawang putih (hiris)"}, {"amount": "\u00bd", "unit": "", "name": "inci halia (hiris)"}, {"amount": "2", "unit": "sudu besar", "name": "sos tiram Kacang panjang (dipotong)"}, {"amount": "1", "unit": "biji", "name": "bawang holland (potong wedges)"}, {"amount": "secukupnya", "unit": "", "name": "10 tangkai cili padi (ikut citarasa (ketuk atau belah sedikit))"}]'::jsonb,
    '["Gaul daging dengan baking soda. Tambah air hingga daging tenggelam. Perap 10-15 minit sahaja.", "Bilas daging 2\u20133 kali hingga bersih, toskan.", "Kemudian, gaul dengan sedikit garam.", "Masukkan daging ke dalam kuali/periuk.", "Tambah air secukupnya hingga menutupi daging.", "Rebus dengan api sederhana hingga daging lembut dan air hampir kering (\u00b115-20 minit). Kacau sekali-sekala supaya tidak melekat.", "Bila air hampir kering, masukkan minyak masak. Masukkan bawang putih dan halia. Tumis hingga wangi dan sedikit garing.", "Masukkan serbuk kunyit, kacau cepat. Masukkan sos tiram, gaul rata.", "Masukkan kacang panjang, bawang holland dan cili padi. Kacau cepat 2\u2013", "3 minit sahaja. Jika terlalu kering boleh masukkan sedikit air.", "Perasakan garam jika perlu. Tutup api dan sedia dihidang."]'::jsonb,
    NULL,
    '["mains", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;
-- Insert / Update recipe: Sambal Belacan Paling Padu (ID: 302)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags
) VALUES (
    302,
    'Sambal Belacan Paling Padu',
    'Sides',
    'Easy',
    '15 min',
    'Aliff Hussien',
    'VOL 17',
    4,
    4.9,
    'published',
    false,
    '[{"amount": "15", "unit": "", "name": "tangkai cili padi"}, {"amount": "3", "unit": "biji", "name": "cili hidup"}, {"amount": "1", "unit": "", "name": "inci belacan bakar"}, {"amount": "\u00bd", "unit": "cawan", "name": "air asam jawa (1 sudu besar pes asam jawa + \u00bd cawan air)"}, {"amount": "1", "unit": "sudu kecil", "name": "garam"}, {"amount": "1", "unit": "sudu besar", "name": "gula"}, {"amount": "3", "unit": "biji", "name": "limau kasturi (buang biji)"}]'::jsonb,
    '["Masukkan semua bahan dalam chopper atau pengisar.", "Kisar kasar tidak terlalu halus.", "Rasa dan suaikan dengan citarasa."]'::jsonb,
    NULL,
    '["sides", "vol17", "premium"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags;

COMMIT;
