-- =========================================================
-- CWC+ VOL 18 - PRODUCTION UPSERT SQL INGESTION SCRIPT
-- Generated on May 2026
-- =========================================================

BEGIN;

-- Media Library Record: QUESADILLA MUDAH (ID: 1801)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1801,
    'quesadilla-mudah.jpeg',
    '/images/recipes/cwc18/quesadilla-mudah.jpeg',
    '/images/recipes/cwc18/quesadilla-mudah.jpeg',
    '/images/recipes/cwc18/quesadilla-mudah.jpeg',
    '#0A1517',
    'QUESADILLA MUDAH',
    'image',
    true,
    '1801',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: QUESADILLA MUDAH (ID: 1801)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1801,
    'QUESADILLA MUDAH',
    'Mains',
    'Intermediate',
    '45m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN TORTILLA"},{"amount":"350","unit":"","name":"tepung gandum"},{"amount":"200","unit":"ml","name":"air panas (didihkan air, ketepikan ±2 minit baru guna)"},{"amount":"1","unit":"sudu kecil","name":"garam (rata)"},{"amount":"2","unit":"sudu besar","name":"minyak sayuran (olive oil, conola etc)"},{"amount":"secukupnya","unit":"","name":"CREAMY SPICY SAUCE"},{"amount":"½","unit":"cawan","name":"mayonis"},{"amount":"¼","unit":"cawan","name":"sour cream (boleh ganti yogurt plain atau mayonis extra)"},{"amount":"2","unit":"sudu besar","name":"cili jeruk / jalapeño cincang/2 biji cili padi cincang (boleh ganti cili hijau jeruk atau cili padi jeruk – guna sikit dulu)"},{"amount":"2","unit":"sudu besar","name":"air jeruk timun (jika tiada, ganti jus limau nipis)"},{"amount":"1","unit":"sudu kecil","name":"sos cili / chili oil"},{"amount":"1","unit":"sudu kecil","name":"serbuk paprika"},{"amount":"½","unit":"sudu kecil","name":"serbuk cili (cayenne / cili biasa)"},{"amount":"1","unit":"sudu kecil","name":"serbuk bawang putih"},{"amount":"1","unit":"sudu kecil","name":"serbuk bawang besar"},{"amount":"1","unit":"sudu kecil","name":"gula"},{"amount":"½","unit":"sudu kecil","name":"garam (atau ikut rasa)"},{"amount":"secukupnya","unit":"","name":"CHICKEN QUESADILLAS (BAHAN PERAP)"},{"amount":"500","unit":"gm","name":"ayam (peha atau dada)"},{"amount":"1","unit":"sudu kecil","name":"serbuk cayenne"},{"amount":"1","unit":"sudu kecil","name":"paprika"},{"amount":"1","unit":"sudu kecil","name":"serbuk jintan putih (cumin)"},{"amount":"1","unit":"sudu kecil","name":"serbuk bawang putih"},{"amount":"1","unit":"sudu kecil","name":"serbuk bawang besar"},{"amount":"1","unit":"sudu kecil","name":"lada hitam"},{"amount":"secukupnya","unit":"","name":"½ sudu kecil perasa tambahan (optional)"},{"amount":"½","unit":"sudu kecil","name":"garam"},{"amount":"secukupnya","unit":"","name":"Jus 1 biji limau nipis/lemon"},{"amount":"secukupnya","unit":"","name":"BAHAN INTI QUESADILLA"},{"amount":"1","unit":"biji","name":"bawang merah/holland (hiris)"},{"amount":"1","unit":"biji","name":"capsicum hijau (hiris)"},{"amount":"1","unit":"biji","name":"capsicum merah (hiris)"},{"amount":"4","unit":"ulas","name":"bawang putih (cincang)"},{"amount":"100","unit":"gm","name":"keju cheddar (parut)"},{"amount":"100","unit":"gm","name":"mozarella /red cheese (parut)"},{"amount":"8","unit":"keping","name":"tortilla wrap"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/quesadilla-mudah.jpeg',
    'https://youtu.be/RDZIG9lY55I?si=ot_KTsHwgybTbhPH',
    1801,
    '/images/recipes/cwc18/quesadilla-mudah.jpeg',
    1801
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: ASAM PEDAS AYAM (ID: 1802)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1802,
    'asam-pedas-ayam.jpeg',
    '/images/recipes/cwc18/asam-pedas-ayam.jpeg',
    '/images/recipes/cwc18/asam-pedas-ayam.jpeg',
    '/images/recipes/cwc18/asam-pedas-ayam.jpeg',
    '#0A1517',
    'ASAM PEDAS AYAM',
    'image',
    true,
    '1802',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: ASAM PEDAS AYAM (ID: 1802)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1802,
    'ASAM PEDAS AYAM',
    'Mains',
    'Intermediate',
    '40m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"1/2","unit":"","name":"ekor ayam"},{"amount":"1","unit":"","name":"½ cawan minyak masak"},{"amount":"1","unit":"batang","name":"serai (diketuk)"},{"amount":"1","unit":"kuntum","name":"bunga kantan (belah dua)"},{"amount":"2","unit":"biji","name":"tomato (belah 4)"},{"amount":"1","unit":"ikat","name":"daun kesum"},{"amount":"secukupnya","unit":"","name":"Air pati asam jawa (ikut tahap masam)"},{"amount":"secukupnya","unit":"","name":"Garam secukup rasa"},{"amount":"secukupnya","unit":"","name":"Air secukupnya untuk kuah"},{"amount":"secukupnya","unit":"","name":"BAHAN KISAR"},{"amount":"15","unit":"biji","name":"cili kering (rendam air panas, buang biji jika nak kurang pedas)"},{"amount":"7","unit":"biji","name":"bawang merah kecil / 3 biji bawang besar (sederhana)"},{"amount":"4","unit":"ulas","name":"bawang putih"},{"amount":"1","unit":"inci","name":"halia"},{"amount":"1","unit":"inci","name":"lengkuas"},{"amount":"1","unit":"ketul","name":"kunyit hidup (besar ibu jari)"},{"amount":"1/2","unit":"inci","name":"belacan (jika suka)"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/asam-pedas-ayam.jpeg',
    'https://youtu.be/snjS1FNBcXI?si=FyJ-_4wDnLoFTRgX',
    1802,
    '/images/recipes/cwc18/asam-pedas-ayam.jpeg',
    1802
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: RENDANG AYAM MUDAH (ID: 1803)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1803,
    'rendang-ayam-mudah.jpeg',
    '/images/recipes/cwc18/rendang-ayam-mudah.jpeg',
    '/images/recipes/cwc18/rendang-ayam-mudah.jpeg',
    '/images/recipes/cwc18/rendang-ayam-mudah.jpeg',
    '#0A1517',
    'RENDANG AYAM MUDAH',
    'image',
    true,
    '1803',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: RENDANG AYAM MUDAH (ID: 1803)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1803,
    'RENDANG AYAM MUDAH',
    'Mains',
    'Intermediate',
    '1j 30m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN KISAR"},{"amount":"20-30","unit":"","name":"tangkai cili kering (rebus/rendam hingga lembut & toskan)"},{"amount":"1","unit":"biji","name":"bawang besar"},{"amount":"7","unit":"biji","name":"bawang merah"},{"amount":"10","unit":"ulas","name":"bawang putih"},{"amount":"2","unit":"batang","name":"serai"},{"amount":"1","unit":"inci","name":"halia"},{"amount":"1","unit":"inci","name":"lengkuas"},{"amount":"2","unit":"ketul","name":"kunyit hidup"},{"amount":"secukupnya","unit":"","name":"Air secukupnya (untuk kisar)"},{"amount":"secukupnya","unit":"","name":"BAHAN LAIN"},{"amount":"1","unit":"","name":"ekor ayam (±1.5kg-1.8kg) – potong sederhana"},{"amount":"1","unit":"helai","name":"daun kunyit – diracik halus"},{"amount":"5","unit":"helai","name":"daun limau purut (dihiris halus)"},{"amount":"2","unit":"batang","name":"serai – dihiris halus"},{"amount":"1","unit":"batang","name":"serai - dititik"},{"amount":"3-4","unit":"keping","name":"asam gelugur / asam keping (ikut citarasa)"},{"amount":"2","unit":"sudu besar","name":"kerisik"},{"amount":"500","unit":"ml","name":"santan pekat (±2 cawan)"},{"amount":"1","unit":"cawan","name":"air (jika perlu)"},{"amount":"50","unit":"g","name":"gula melaka (secukup rasa)"},{"amount":"secukupnya","unit":"","name":"Gula pasir secukup rasa"},{"amount":"secukupnya","unit":"","name":"Garam secukup rasa"},{"amount":"secukupnya","unit":"","name":"Minyak masak secukupnya untuk menumis"}]'::jsonb,
    '[]'::jsonb,
    '["Resepi ini juga sesuai untuk rendang daging, cuma masa memasak perlu lebih lama.","Boleh adjust tahap pedas, masin & manis ikut citarasa sendiri.","Elakkan kacau terlalu kerap di hujung masakan supaya ayam tidak hancur."]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/rendang-ayam-mudah.jpeg',
    'https://youtu.be/mPgeIo4ekPA?si=a8b03F2qiuSx04hB',
    1803,
    '/images/recipes/cwc18/rendang-ayam-mudah.jpeg',
    1803
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: PULUT KUNING MUDAH (ID: 1804)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1804,
    'pulut-kuning-mudah.jpeg',
    '/images/recipes/cwc18/pulut-kuning-mudah.jpeg',
    '/images/recipes/cwc18/pulut-kuning-mudah.jpeg',
    '/images/recipes/cwc18/pulut-kuning-mudah.jpeg',
    '#0A1517',
    'PULUT KUNING MUDAH',
    'image',
    true,
    '1804',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: PULUT KUNING MUDAH (ID: 1804)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1804,
    'PULUT KUNING MUDAH',
    'Mains',
    'Intermediate',
    '45m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"1","unit":"","name":"kg beras pulut"},{"amount":"secukupnya","unit":"","name":"Air secukupnya (paras ±1–1½ cm atas pulut- teknik jari )"},{"amount":"1","unit":"","name":"½ – 2 sudu kecil serbuk kunyit ATAU kunyit hidup (ditumbuk & diperah)"},{"amount":"1","unit":"","name":"¼ sudu kecil garam (secukup rasa)"},{"amount":"1","unit":"kotak","name":"kecil santan (±200 ml)"},{"amount":"3","unit":"helai","name":"daun pandan (disimpul)"},{"amount":"1","unit":"sudu besar","name":"minyak masak (opsyenal – bagi pulut berkilat)"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/pulut-kuning-mudah.jpeg',
    'https://youtu.be/mPgeIo4ekPA?si=a8b03F2qiuSx04hB',
    1804,
    '/images/recipes/cwc18/pulut-kuning-mudah.jpeg',
    1804
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: EASY DELICIOUS BREAKFAST (ID: 1805)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1805,
    'easy-delicious-breakfast.jpeg',
    '/images/recipes/cwc18/easy-delicious-breakfast.jpeg',
    '/images/recipes/cwc18/easy-delicious-breakfast.jpeg',
    '/images/recipes/cwc18/easy-delicious-breakfast.jpeg',
    '#0A1517',
    'EASY DELICIOUS BREAKFAST',
    'image',
    true,
    '1805',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: EASY DELICIOUS BREAKFAST (ID: 1805)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1805,
    'EASY DELICIOUS BREAKFAST',
    'Mains',
    'Intermediate',
    '15m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"1","unit":"keping","name":"tortilla"},{"amount":"2","unit":"biji","name":"telur"},{"amount":"1","unit":"biji","name":"tomato (dadu kecil)"},{"amount":"3","unit":"sudu besar","name":"mozzarella/cheddar (parut / hiris)"},{"amount":"1","unit":"batang","name":"daun bawang (hiris halus)"},{"amount":"1","unit":"sudu kecil","name":"butter/minyak"},{"amount":"secukupnya","unit":"","name":"Garam secukup rasa"},{"amount":"secukupnya","unit":"","name":"Serbuk lada hitam secukup rasa"},{"amount":"secukupnya","unit":"","name":"Oregano secukup rasa - jika ada"},{"amount":"secukupnya","unit":"","name":"Basil kering secukup rasa -jika ada"},{"amount":"secukupnya","unit":"","name":"Serbuk bawang putih kering (dried garlic) secukup rasa"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/easy-delicious-breakfast.jpeg',
    'https://youtu.be/v2ybLrZehGA?si=mlil2bGlTly3j8oC',
    1805,
    '/images/recipes/cwc18/easy-delicious-breakfast.jpeg',
    1805
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: DAGING MASAK MERAH ALA THAI (ID: 1806)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1806,
    'daging-masak-merah-ala-thai.jpeg',
    '/images/recipes/cwc18/daging-masak-merah-ala-thai.jpeg',
    '/images/recipes/cwc18/daging-masak-merah-ala-thai.jpeg',
    '/images/recipes/cwc18/daging-masak-merah-ala-thai.jpeg',
    '#0A1517',
    'DAGING MASAK MERAH ALA THAI',
    'image',
    true,
    '1806',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: DAGING MASAK MERAH ALA THAI (ID: 1806)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1806,
    'DAGING MASAK MERAH ALA THAI',
    'Mains',
    'Intermediate',
    '1j',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"½","unit":"","name":"kg daging lembu (rebus- hiris nipis lawan urat)"},{"amount":"secukupnya","unit":"","name":"Air rebusan daging (secukupnya)"},{"amount":"secubit","unit":"","name":"garam"},{"amount":"1","unit":"sudu kecil","name":"pewarna merah (optional)"},{"amount":"1","unit":"batang","name":"serai (dititik)"},{"amount":"8","unit":"helai","name":"daun limau purut (buang urat, carik)"},{"amount":"secukupnya","unit":"","name":"I biji tomato (belah 4)"},{"amount":"1","unit":"","name":"o tangkai cili padi (belah/ketuk)"},{"amount":"½","unit":"batang","name":"lobak merah (hiris nipis)"},{"amount":"½","unit":"biji","name":"bawang holland (potong wedges)"},{"amount":"1","unit":"sudu besar","name":"gula nisan Thai/gula melaka"},{"amount":"1","unit":"","name":"½ sudu besar sos tiram"},{"amount":"2","unit":"sudu besar","name":"sos tomato"},{"amount":"2","unit":"sudu besar","name":"sos cili"},{"amount":"3","unit":"sudu besar","name":"sos ikan"},{"amount":"½","unit":"sudu kecil","name":"kicap cair"},{"amount":"1","unit":"biji","name":"limau nipis (perahan)"},{"amount":"1","unit":"","name":"tangkai daun ketumbar (tabur- akar masuk dalam kuah)"},{"amount":"1","unit":"cawan","name":"rebus daging (secukupnya)"},{"amount":"secukupnya","unit":"","name":"BAHAN TUMIS"},{"amount":"4","unit":"ulas","name":"bawang putih (cincang)"},{"amount":"1","unit":"inci","name":"halia (cincang)"},{"amount":"2-3","unit":"sudu besar","name":"cili kering (ikut citarasa)"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/daging-masak-merah-ala-thai.jpeg',
    'https://youtu.be/MUOanUrNbOY?si=fLN0S6aUbQsp4Jz2',
    1806,
    '/images/recipes/cwc18/daging-masak-merah-ala-thai.jpeg',
    1806
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: BANANA OATMEAL MUFFIN (ID: 1807)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1807,
    'banana-oatmeal-muffin.jpeg',
    '/images/recipes/cwc18/banana-oatmeal-muffin.jpeg',
    '/images/recipes/cwc18/banana-oatmeal-muffin.jpeg',
    '/images/recipes/cwc18/banana-oatmeal-muffin.jpeg',
    '#0A1517',
    'BANANA OATMEAL MUFFIN',
    'image',
    true,
    '1807',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: BANANA OATMEAL MUFFIN (ID: 1807)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1807,
    'BANANA OATMEAL MUFFIN',
    'Mains',
    'Intermediate',
    '35m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"2","unit":"cawan","name":"oat (±200 g) – kisar jadi tepung oat"},{"amount":"1","unit":"sudu kecil","name":"serbuk penaik (baking powder)"},{"amount":"½","unit":"sudu kecil","name":"soda bikarbonat"},{"amount":"¼","unit":"sudu kecil","name":"garam"},{"amount":"½","unit":"sudu kecil","name":"serbuk kayu manis"},{"amount":"3","unit":"biji","name":"pisang masak ranum (300gm) – lenyek"},{"amount":"½","unit":"cawan","name":"minyak (120 ml)"},{"amount":"½","unit":"cawan","name":"gula atau madu (±100 g) - boleh kurangkan gula atau tak letak"},{"amount":"1","unit":"sudu kecil","name":"esen vanila"},{"amount":"2","unit":"biji","name":"telur (gred A/B)"},{"amount":"1","unit":"cawan","name":"(120gm) campuran kismis / coklat cip / walnut etc"}]'::jsonb,
    '[]'::jsonb,
    '["Tips penting bila tak guna gula: Rasa muffin akan kurang manis, tapi sedap & sesuai untuk diet / kanak-kanak. Tekstur tetap moist sebab ada pisang + minyak.","Pilihan kalau nak manis sikit (optional): Tambah kismis atau chocolate chips atau gantikan with: 1–2 sudu besar madu / 1–2 sudu besar maple syrup."]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/banana-oatmeal-muffin.jpeg',
    'https://youtu.be/vaKwckfDQy0?si=XkwXvg3mOrcyxsiG',
    1807,
    '/images/recipes/cwc18/banana-oatmeal-muffin.jpeg',
    1807
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: KERABU IKAN BILIS MUDAH (ID: 1808)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1808,
    'kerabu-ikan-bilis-mudah.jpeg',
    '/images/recipes/cwc18/kerabu-ikan-bilis-mudah.jpeg',
    '/images/recipes/cwc18/kerabu-ikan-bilis-mudah.jpeg',
    '/images/recipes/cwc18/kerabu-ikan-bilis-mudah.jpeg',
    '#0A1517',
    'KERABU IKAN BILIS MUDAH',
    'image',
    true,
    '1808',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: KERABU IKAN BILIS MUDAH (ID: 1808)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1808,
    'KERABU IKAN BILIS MUDAH',
    'Mains',
    'Intermediate',
    '20m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"2","unit":"","name":"genggam ikan bilis (ikut citarasa)"},{"amount":"2","unit":"kuntum","name":"bunga kantan – hiris halus"},{"amount":"1","unit":"batang","name":"serai – hiris halus"},{"amount":"secukupnya","unit":"","name":"Daun kesum – hiris halus (jika suka)"},{"amount":"3","unit":"biji","name":"cili padi hijau – hiris"},{"amount":"3","unit":"biji","name":"cili padi merah – hiris"},{"amount":"1/2","unit":"biji","name":"tomato – potong dadu kecil (jika suka)"},{"amount":"2","unit":"","name":"tangkai kacang panjang - potong halus"},{"amount":"1","unit":"sudu besar","name":"gula perang (secukup rasa)"},{"amount":"1/2","unit":"sudu besar","name":"sos ikan"},{"amount":"1","unit":"","name":"½ sudu besar jus perahan limau nipis (secukup rasa)"}]'::jsonb,
    '[]'::jsonb,
    '["Sedap di makan bersama telur mata and kicap."]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/kerabu-ikan-bilis-mudah.jpeg',
    'https://youtu.be/vaKwckfDQy0?si=XkwXvg3mOrcyxsiG',
    1808,
    '/images/recipes/cwc18/kerabu-ikan-bilis-mudah.jpeg',
    1808
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: HOMEMADE BAGELS (ID: 1809)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1809,
    'homemade-bagels.jpeg',
    '/images/recipes/cwc18/homemade-bagels.jpeg',
    '/images/recipes/cwc18/homemade-bagels.jpeg',
    '/images/recipes/cwc18/homemade-bagels.jpeg',
    '#0A1517',
    'HOMEMADE BAGELS',
    'image',
    true,
    '1809',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: HOMEMADE BAGELS (ID: 1809)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1809,
    'HOMEMADE BAGELS',
    'Mains',
    'Intermediate',
    '1j 15m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN DOH BAGEL"},{"amount":"secukupnya","unit":"","name":"Tepung Gandum/roti : 390 g (≈3 cawan loosely packed)"},{"amount":"secukupnya","unit":"","name":"Air suam: 270 ml (1 cawan + 2 sudu)"},{"amount":"secukupnya","unit":"","name":"Garam: 6 g (1 sudu teh)"},{"amount":"secukupnya","unit":"","name":"Gula: 12 g (1 sudu besar)"},{"amount":"secukupnya","unit":"","name":"Yis: 3 g (1 sudu teh) — jika guna active dry yeast: 1 ¼ sudu teh"},{"amount":"secukupnya","unit":"","name":"UNTUK TABURAN ATAS BAGEL"},{"amount":"secukupnya","unit":"","name":"Bijan, garam flakey, bawang putih cincang, biji poppy, dsb."}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/homemade-bagels.jpeg',
    'https://youtu.be/xf6HvLNYDTY?si=Mu94PrPSPPjIv9oy',
    1809,
    '/images/recipes/cwc18/homemade-bagels.jpeg',
    1809
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: UDANG MASAK ALA DI RAJA (ID: 1810)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1810,
    'udang-masak-ala-di-raja.jpeg',
    '/images/recipes/cwc18/udang-masak-ala-di-raja.jpeg',
    '/images/recipes/cwc18/udang-masak-ala-di-raja.jpeg',
    '/images/recipes/cwc18/udang-masak-ala-di-raja.jpeg',
    '#0A1517',
    'UDANG MASAK ALA DI RAJA',
    'image',
    true,
    '1810',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: UDANG MASAK ALA DI RAJA (ID: 1810)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1810,
    'UDANG MASAK ALA DI RAJA',
    'Mains',
    'Intermediate',
    '25m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"1","unit":"","name":"kg udang saiz besar (buang urat, potong misai)"},{"amount":"2","unit":"batang","name":"serai (di ketuk)"},{"amount":"3","unit":"helai","name":"daun kunyit (hiris halus)"},{"amount":"1","unit":"helai","name":"daun pandan simpul (optional)"},{"amount":"1","unit":"sudu kecil","name":"gula (secukup rasa)"},{"amount":"sedikit","unit":"","name":"serbuk perasa (optional)"},{"amount":"2-3","unit":"keping","name":"asam keping (secukup rasa)"},{"amount":"1","unit":"kotak","name":"kecil santan / 200ml santan segar (pekat)"},{"amount":"sedikit","unit":"","name":"air (secukupnya)"},{"amount":"secukupnya","unit":"","name":"Minyak masak (secukupnya)"},{"amount":"secukupnya","unit":"","name":"BAHAN KISAR"},{"amount":"5","unit":"biji","name":"bawang besar (saiz sederhana)"},{"amount":"5","unit":"ulas","name":"bawang putih"},{"amount":"1","unit":"inci","name":"halia"},{"amount":"1","unit":"inci","name":"kunyit hidup"},{"amount":"1","unit":"inci","name":"lengkuas"},{"amount":"3","unit":"batang","name":"cili hidup merah"},{"amount":"10-15","unit":"biji","name":"cili padi hijau"}]'::jsonb,
    '[]'::jsonb,
    '["Sedap makan with nasi putih panas / nasi minyak / nasi hujan panas."]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/udang-masak-ala-di-raja.jpeg',
    'https://youtu.be/xf6HvLNYDTY?si=Mu94PrPSPPjIv9oy',
    1810,
    '/images/recipes/cwc18/udang-masak-ala-di-raja.jpeg',
    1810
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: SUP AYAM BERSANTAN ALA THAI (TOM KHA GAI) (ID: 1811)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1811,
    'sup-ayam-bersantan-ala-thai-tom-kha-gai.jpeg',
    '/images/recipes/cwc18/sup-ayam-bersantan-ala-thai-tom-kha-gai.jpeg',
    '/images/recipes/cwc18/sup-ayam-bersantan-ala-thai-tom-kha-gai.jpeg',
    '/images/recipes/cwc18/sup-ayam-bersantan-ala-thai-tom-kha-gai.jpeg',
    '#0A1517',
    'SUP AYAM BERSANTAN ALA THAI (TOM KHA GAI)',
    'image',
    true,
    '1811',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: SUP AYAM BERSANTAN ALA THAI (TOM KHA GAI) (ID: 1811)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1811,
    'SUP AYAM BERSANTAN ALA THAI (TOM KHA GAI)',
    'Mains',
    'Intermediate',
    '25m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"2","unit":"cawan","name":"stok ayam (tanpa garam Atau Air sahaja)"},{"amount":"1","unit":"","name":"½ cawan santan (250ml) / 1 santan kotak (kecil)"},{"amount":"½","unit":"sudu kecil","name":"garam"},{"amount":"secukupnya","unit":"","name":"±450g isi ayam peha tanpa tulang & kulit – potong kiub ±1 inci"},{"amount":"1","unit":"batang","name":"serai – bahagian bawah sahaja, diketuk & potong 2 inci"},{"amount":"12","unit":"","name":"hiris nipis lengkuas"},{"amount":"5","unit":"helai","name":"daun limau purut – disiat & diramas"},{"amount":"1","unit":"","name":"3 biji cili padi Thai – diketuk (ikut tahap pedas)"},{"amount":"2","unit":"sudu besar","name":"sos ikan"},{"amount":"1","unit":"sudu kecil","name":"gula melaka cincang / gula pasir"},{"amount":"100","unit":"g","name":"cendawan tiram – disiat sederhana"},{"amount":"2","unit":"","name":"½ sudu besar jus limau nipis"},{"amount":"secukupnya","unit":"","name":"Daun ketumbar – untuk hiasan"},{"amount":"secukupnya","unit":"","name":"Nasi jasmine – optional (untuk hidangan)"}]'::jsonb,
    '[]'::jsonb,
    '["Serai, lengkuas & daun limau purut untuk aroma sahaja, tidak dimakan (Boleh keluarkan sebelum hidang atau inform tetamu.)","Versi lebih ringan: Kurangkan santan ½ cawan & tambah stok ayam ½ cawan."]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/sup-ayam-bersantan-ala-thai-tom-kha-gai.jpeg',
    'https://youtu.be/cE3MK0yqEh4?si=xr7a-3PRq9Rgc_9E',
    1811,
    '/images/recipes/cwc18/sup-ayam-bersantan-ala-thai-tom-kha-gai.jpeg',
    1811
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: TAUHU BERLAUK CWC (ID: 1812)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1812,
    'tauhu-berlauk-cwc.jpeg',
    '/images/recipes/cwc18/tauhu-berlauk-cwc.jpeg',
    '/images/recipes/cwc18/tauhu-berlauk-cwc.jpeg',
    '/images/recipes/cwc18/tauhu-berlauk-cwc.jpeg',
    '#0A1517',
    'TAUHU BERLAUK CWC',
    'image',
    true,
    '1812',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: TAUHU BERLAUK CWC (ID: 1812)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1812,
    'TAUHU BERLAUK CWC',
    'Mains',
    'Intermediate',
    '45m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"4","unit":"","name":"pcs tauhu telur"},{"amount":"3","unit":"","name":"pcs tauhu putih (4 ketul jika nak adunan sedikit pekat)"},{"amount":"200-250","unit":"gm","name":"isi ayam"},{"amount":"1","unit":"","name":"pokok daun sup/daun ketumbar – hiris halus"},{"amount":"1","unit":"biji","name":"bawang besar – cincang halus"},{"amount":"2","unit":"","name":"tangkai cili padi – hiris halus"},{"amount":"½","unit":"batang","name":"lobak merah – parut halus"},{"amount":"3","unit":"biji","name":"telur"},{"amount":"1","unit":"","name":"kiub pati ayam"},{"amount":"2","unit":"sudu kecil","name":"serbuk lada sulah"},{"amount":"1","unit":"sudu kecil","name":"garam (ikut rasa -boleh skip)"},{"amount":"secukupnya","unit":"","name":"BAHAN SALUTAN GORENG"},{"amount":"2","unit":"biji","name":"telur"},{"amount":"1","unit":"sudu besar","name":"tepung jagung"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/tauhu-berlauk-cwc.jpeg',
    'https://youtu.be/ScjUa5_dW98?si=8roOWpR-oVoaCO2A',
    1812,
    '/images/recipes/cwc18/tauhu-berlauk-cwc.jpeg',
    1812
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: SAMBAL KICAP PADU (ID: 1813)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1813,
    'sambal-kicap-padu.jpeg',
    '/images/recipes/cwc18/sambal-kicap-padu.jpeg',
    '/images/recipes/cwc18/sambal-kicap-padu.jpeg',
    '/images/recipes/cwc18/sambal-kicap-padu.jpeg',
    '#0A1517',
    'SAMBAL KICAP PADU',
    'image',
    true,
    '1813',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: SAMBAL KICAP PADU (ID: 1813)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1813,
    'SAMBAL KICAP PADU',
    'Condiments',
    'Intermediate',
    '10m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"4","unit":"ulas","name":"bawang putih"},{"amount":"½","unit":"biji","name":"bawang besar"},{"amount":"8","unit":"","name":"tangkai cili padi (ikut tahap kepedasan)"},{"amount":"3/4","unit":"cawan","name":"kicap manis"},{"amount":"½","unit":"sudu kecil","name":"garam"},{"amount":"1","unit":"sudu besar","name":"gula"},{"amount":"sedikit","unit":"","name":"minyak masak"}]'::jsonb,
    '[]'::jsonb,
    '["Siap untuk dihidang bersama tauhu berlauk."]'::jsonb,
    '["vol18","premium","condiments"]'::jsonb,
    '/images/recipes/cwc18/sambal-kicap-padu.jpeg',
    'https://youtu.be/ScjUa5_dW98?si=8roOWpR-oVoaCO2A',
    1813,
    '/images/recipes/cwc18/sambal-kicap-padu.jpeg',
    1813
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: CRAZY NUTTY COOKIES (ID: 1814)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1814,
    'crazy-nutty-cookies.jpeg',
    '/images/recipes/cwc18/crazy-nutty-cookies.jpeg',
    '/images/recipes/cwc18/crazy-nutty-cookies.jpeg',
    '/images/recipes/cwc18/crazy-nutty-cookies.jpeg',
    '#0A1517',
    'CRAZY NUTTY COOKIES',
    'image',
    true,
    '1814',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: CRAZY NUTTY COOKIES (ID: 1814)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1814,
    'CRAZY NUTTY COOKIES',
    'Desserts',
    'Intermediate',
    '25m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"1","unit":"","name":"Tepung florentin (Bienetta) 500 gram"},{"amount":"3 1/2","unit":"cawan","name":"kekacang pilihan (di panggang)"},{"amount":"secukupnya","unit":"","name":"Paper cup/acuan secukupnya"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","desserts"]'::jsonb,
    '/images/recipes/cwc18/crazy-nutty-cookies.jpeg',
    'https://youtu.be/Ey_rHS5S37Y?si=hGlYFNDn-uz4Krh9',
    1814,
    '/images/recipes/cwc18/crazy-nutty-cookies.jpeg',
    1814
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: DAGING BERLADO ALA PADANG (ID: 1815)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1815,
    'daging-berlado-ala-padang.jpeg',
    '/images/recipes/cwc18/daging-berlado-ala-padang.jpeg',
    '/images/recipes/cwc18/daging-berlado-ala-padang.jpeg',
    '/images/recipes/cwc18/daging-berlado-ala-padang.jpeg',
    '#0A1517',
    'DAGING BERLADO ALA PADANG',
    'image',
    true,
    '1815',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: DAGING BERLADO ALA PADANG (ID: 1815)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1815,
    'DAGING BERLADO ALA PADANG',
    'Mains',
    'Intermediate',
    '1j 15m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"500","unit":"gm","name":"daging lembu (bahagian pejal – batang pinang / topside)"},{"amount":"1","unit":"inci","name":"halia - kisar kasar"},{"amount":"1","unit":"batang","name":"serai - kisar kasar"},{"amount":"2","unit":"ulas","name":"bawang putih - kisar kasar"},{"amount":"3","unit":"helai","name":"daun salam (kering atau fresh)"},{"amount":"1","unit":"sudu besar","name":"serbuk ketumbar"},{"amount":"secukupnya","unit":"","name":"Garam secukup rasa"},{"amount":"secukupnya","unit":"","name":"Gula secukup rasa"},{"amount":"secukupnya","unit":"","name":"Minyak secukupnya"},{"amount":"secukupnya","unit":"","name":"Air secukupnya (untuk rebus)"},{"amount":"secukupnya","unit":"","name":"BAHAN TUMISAN"},{"amount":"5","unit":"biji","name":"cili merah besar"},{"amount":"8-10","unit":"biji","name":"cili padi merah (ikut tahap pedas)"},{"amount":"1","unit":"biji","name":"tomato merah masak"},{"amount":"6","unit":"biji","name":"bawang merah kecil/ 3 biji bawang besar"},{"amount":"3","unit":"ulas","name":"bawang putih"},{"amount":"secukupnya","unit":"","name":"Goreng seketika. Kisar kasar semua bahan di atas tanpa air, jangan terlalu halus."}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/daging-berlado-ala-padang.jpeg',
    'https://youtu.be/Ey_rHS5S37Y?si=hGlYFNDn-uz4Krh9',
    1815,
    '/images/recipes/cwc18/daging-berlado-ala-padang.jpeg',
    1815
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: SAMBAL IKAN BILIS GARING (ID: 1816)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1816,
    'sambal-ikan-bilis-garing.jpeg',
    '/images/recipes/cwc18/sambal-ikan-bilis-garing.jpeg',
    '/images/recipes/cwc18/sambal-ikan-bilis-garing.jpeg',
    '/images/recipes/cwc18/sambal-ikan-bilis-garing.jpeg',
    '#0A1517',
    'SAMBAL IKAN BILIS GARING',
    'image',
    true,
    '1816',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: SAMBAL IKAN BILIS GARING (ID: 1816)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1816,
    'SAMBAL IKAN BILIS GARING',
    'Snacks',
    'Intermediate',
    '30m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"150","unit":"g","name":"bawang merah"},{"amount":"100","unit":"g","name":"ikan bilis"},{"amount":"10-15","unit":"","name":"tangkai cili kering (ikut citarasa)"},{"amount":"1","unit":"sudu besar","name":"gula"},{"amount":"secukupnya","unit":"","name":"Garam secukupnya"},{"amount":"secukupnya","unit":"","name":"Minyak masak secukupnya untuk menggoreng"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","snacks"]'::jsonb,
    '/images/recipes/cwc18/sambal-ikan-bilis-garing.jpeg',
    'https://youtu.be/JHDt2wbmmG4?si=CuylFvlxXZMZvAHB',
    1816,
    '/images/recipes/cwc18/sambal-ikan-bilis-garing.jpeg',
    1816
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: CREAMY TOMYAM PASTA 2.0 (ID: 1817)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1817,
    'creamy-tomyam-pasta-2-0.jpeg',
    '/images/recipes/cwc18/creamy-tomyam-pasta-2-0.jpeg',
    '/images/recipes/cwc18/creamy-tomyam-pasta-2-0.jpeg',
    '/images/recipes/cwc18/creamy-tomyam-pasta-2-0.jpeg',
    '#0A1517',
    'CREAMY TOMYAM PASTA 2.0',
    'image',
    true,
    '1817',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: CREAMY TOMYAM PASTA 2.0 (ID: 1817)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1817,
    'CREAMY TOMYAM PASTA 2.0',
    'Desserts',
    'Intermediate',
    '30m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"500","unit":"g","name":"spaghetti (rebus bersama sedikit garam hingga al dente)"},{"amount":"1","unit":"biji","name":"bawang Holland (potong dadu)"},{"amount":"4","unit":"ulas","name":"bawang putih (potong dadu)"},{"amount":"150","unit":"g","name":"udang (buang kulit & bersihkan)"},{"amount":"20","unit":"g","name":"mentega (±2 sudu besar, optional)"},{"amount":"20","unit":"g","name":"minyak zaitun"},{"amount":"3","unit":"helai","name":"daun limau purut (carik dan buang tulang tengah)"},{"amount":"2","unit":"","name":"kiub tomyam atau 2 sudu besar pes tomyam"},{"amount":"1","unit":"biji","name":"tomato (potong dadu)"},{"amount":"1","unit":"sudu kecil","name":"garam"},{"amount":"1","unit":"sudu kecil","name":"serbuk pati ayam / 1 kiub ayam"},{"amount":"1","unit":"sudu besar","name":"chilli flakes"},{"amount":"3","unit":"batang","name":"cili padi (hiris halus, optional)"},{"amount":"secukupnya","unit":"","name":"Segenggam baby spinach"},{"amount":"200","unit":"g","name":"cooking cream atau santan"},{"amount":"500","unit":"ml","name":"air"},{"amount":"5","unit":"sudu makan","name":"air rebusan pasta"},{"amount":"secukupnya","unit":"","name":"Perahan air limau nipis (optional)"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","desserts"]'::jsonb,
    '/images/recipes/cwc18/creamy-tomyam-pasta-2-0.jpeg',
    'https://youtu.be/hqUkBPKV3Vk?si=l4SbhfLPyPSvoMwH',
    1817,
    '/images/recipes/cwc18/creamy-tomyam-pasta-2-0.jpeg',
    1817
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: EASY LOVE COOKIES (ID: 1818)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1818,
    'easy-love-cookies.jpeg',
    '/images/recipes/cwc18/easy-love-cookies.jpeg',
    '/images/recipes/cwc18/easy-love-cookies.jpeg',
    '/images/recipes/cwc18/easy-love-cookies.jpeg',
    '#0A1517',
    'EASY LOVE COOKIES',
    'image',
    true,
    '1818',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: EASY LOVE COOKIES (ID: 1818)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1818,
    'EASY LOVE COOKIES',
    'Desserts',
    'Intermediate',
    '35m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"113","unit":"g","name":"butter/ mentega (½ cup), lembutkan"},{"amount":"67","unit":"g","name":"gula (¼ cup + 1 tbsp)"},{"amount":"146","unit":"g","name":"tepung gandum (1 cup + 2 tbsp)"},{"amount":"40","unit":"g","name":"jem (±2 tbsp – strawberry, raspberry, apricot atau ikut suka)"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","desserts"]'::jsonb,
    '/images/recipes/cwc18/easy-love-cookies.jpeg',
    'https://youtu.be/RBKMbV5XvGw?si=t97xysKizKZ1u6mj',
    1818,
    '/images/recipes/cwc18/easy-love-cookies.jpeg',
    1818
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: SOTONG KAM HEONG (ID: 1819)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1819,
    'sotong-kam-heong.jpeg',
    '/images/recipes/cwc18/sotong-kam-heong.jpeg',
    '/images/recipes/cwc18/sotong-kam-heong.jpeg',
    '/images/recipes/cwc18/sotong-kam-heong.jpeg',
    '#0A1517',
    'SOTONG KAM HEONG',
    'image',
    true,
    '1819',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: SOTONG KAM HEONG (ID: 1819)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1819,
    'SOTONG KAM HEONG',
    'Mains',
    'Intermediate',
    '20m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"350","unit":"g","name":"sotong (bersihkan & potong cincin)"},{"amount":"½","unit":"sudu besar","name":"tepung jagung"},{"amount":"4","unit":"ulas","name":"bawang putih (cincang)"},{"amount":"6","unit":"ulas","name":"bawang merah (hiris)"},{"amount":"1","unit":"sudu besar","name":"udang kering (rendam & tumbuk kasar)"},{"amount":"1","unit":"batang","name":"serai (titik)"},{"amount":"3-5","unit":"","name":"tangkai cili padi (hiris)"},{"amount":"1","unit":"","name":"½ sudu besar serbuk kari daging/Ayam"},{"amount":"5","unit":"","name":"tangkai daun kari"},{"amount":"1","unit":"sudu besar","name":"cili kisar"},{"amount":"1","unit":"sudu kecil","name":"kicap pekat"},{"amount":"1","unit":"sudu kecil","name":"light soy sauce (kicap cair)"},{"amount":"1","unit":"sudu kecil","name":"gula"},{"amount":"1","unit":"sudu besar","name":"sos tiram"},{"amount":"25","unit":"ml","name":"air"},{"amount":"secukupnya","unit":"","name":"Minyak masak secukupnya"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/sotong-kam-heong.jpeg',
    NULL,
    1819,
    '/images/recipes/cwc18/sotong-kam-heong.jpeg',
    1819
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: SAYUR KAILAN TUMIS SEMPOI (ID: 1820)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1820,
    'sayur-kailan-tumis-sempoi.jpeg',
    '/images/recipes/cwc18/sayur-kailan-tumis-sempoi.jpeg',
    '/images/recipes/cwc18/sayur-kailan-tumis-sempoi.jpeg',
    '/images/recipes/cwc18/sayur-kailan-tumis-sempoi.jpeg',
    '#0A1517',
    'SAYUR KAILAN TUMIS SEMPOI',
    'image',
    true,
    '1820',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: SAYUR KAILAN TUMIS SEMPOI (ID: 1820)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1820,
    'SAYUR KAILAN TUMIS SEMPOI',
    'Mains',
    'Intermediate',
    '10m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN UTAMA"},{"amount":"1","unit":"ikat","name":"baby kailan (potong 2–3 inci, cuci & toskan betul-betul)"},{"amount":"1/2","unit":"batang","name":"lobak merah (potong ikut citarasa)"},{"amount":"1","unit":"batang","name":"cili hidup (hiris)"},{"amount":"4","unit":"ulas","name":"bawang putih (cincang kasar)"},{"amount":"2","unit":"sudu besar","name":"sos tiram"},{"amount":"2","unit":"sudu kecil","name":"kicap cair"},{"amount":"secukupnya","unit":"","name":"Air secukupnya"},{"amount":"secukupnya","unit":"","name":"Garam secukup rasa"},{"amount":"sedikit","unit":"","name":"lada sulah"},{"amount":"2","unit":"sudu besar","name":"minyak masak"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","mains"]'::jsonb,
    '/images/recipes/cwc18/sayur-kailan-tumis-sempoi.jpeg',
    NULL,
    1820,
    '/images/recipes/cwc18/sayur-kailan-tumis-sempoi.jpeg',
    1820
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

-- Media Library Record: SAMBAL GORENG JAWA VERSI SIMPLE (ID: 1821)
INSERT INTO public.media_library (
    id,
    filename,
    hero_url,
    thumb_url,
    card_url,
    dominant_color,
    seo_schema,
    type,
    is_primary,
    content_id,
    content_type,
    meta_data
) VALUES (
    1821,
    'sambal-goreng-jawa-versi-simple.jpeg',
    '/images/recipes/cwc18/sambal-goreng-jawa-versi-simple.jpeg',
    '/images/recipes/cwc18/sambal-goreng-jawa-versi-simple.jpeg',
    '/images/recipes/cwc18/sambal-goreng-jawa-versi-simple.jpeg',
    '#0A1517',
    'SAMBAL GORENG JAWA VERSI SIMPLE',
    'image',
    true,
    '1821',
    'recipe',
    '{"width": 800, "height": 800}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    filename = EXCLUDED.filename,
    hero_url = EXCLUDED.hero_url,
    thumb_url = EXCLUDED.thumb_url,
    card_url = EXCLUDED.card_url,
    dominant_color = EXCLUDED.dominant_color,
    seo_schema = EXCLUDED.seo_schema,
    type = EXCLUDED.type,
    is_primary = EXCLUDED.is_primary,
    content_id = EXCLUDED.content_id,
    content_type = EXCLUDED.content_type,
    meta_data = EXCLUDED.meta_data;

-- Recipe Record: SAMBAL GORENG JAWA VERSI SIMPLE (ID: 1821)
INSERT INTO public.recipes (
    id,
    title, 
    category, 
    difficulty, 
    time, 
    author, 
    volume, 
    base_servings, 
    rating, 
    status, 
    is_featured, 
    ingredients, 
    steps, 
    notes, 
    tags,
    image,
    video,
    cover_image_id,
    hero_image,
    hero_image_id
) VALUES (
    1821,
    'SAMBAL GORENG JAWA VERSI SIMPLE',
    'Condiments',
    'Intermediate',
    '40m',
    'Aliff Hussien',
    'VOL 18',
    4,
    4.9,
    'published',
    false,
    '[{"amount":"secukupnya","unit":"","name":"BAHAN KISAR"},{"amount":"3","unit":"biji","name":"bawang merah/ 1 biji bawang besar"},{"amount":"3","unit":"ulas","name":"bawang putih"},{"amount":"1","unit":"inci","name":"halia"},{"amount":"1","unit":"inci","name":"lengkuas"},{"amount":"4","unit":"","name":"tangkai cili padi"},{"amount":"1/2","unit":"cawan","name":"ikan bilis"},{"amount":"1/2","unit":"cawan","name":"air"},{"amount":"secukupnya","unit":"","name":"BAHAN DIGORENG"},{"amount":"2","unit":"ketul","name":"tauhu (potong kiub)"},{"amount":"2","unit":"biji","name":"kentang (potong kiub)"},{"amount":"2","unit":"keping","name":"tempe (potong kiub)"},{"amount":"1/2","unit":"sudu kecil","name":"garam"},{"amount":"1/2","unit":"sudu kecil","name":"serbuk kunyit"},{"amount":"secukupnya","unit":"","name":"BAHAN LAIN"},{"amount":"1","unit":"batang","name":"serai (dititik)"},{"amount":"6","unit":"batang","name":"kacang panjang (potong 2 inci)"},{"amount":"2","unit":"","name":"tangkai cili merah (hiris)"},{"amount":"1","unit":"","name":"genggam fucuk (rendam lembut)"},{"amount":"1","unit":"","name":"genggam suhun (rendam lembut)"},{"amount":"4","unit":"sudu besar","name":"air asam jawa"},{"amount":"5","unit":"","name":"ekor udang (saiz sederhana)"},{"amount":"100","unit":"ml","name":"santan pekat (1 mangkuk)"},{"amount":"2-3","unit":"sudu besar","name":"kicap manis"},{"amount":"secukupnya","unit":"","name":"Garam secukupnya"},{"amount":"secukupnya","unit":"","name":"Gula melaka (kurangkan sebab ada kicap)"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '["vol18","premium","condiments"]'::jsonb,
    '/images/recipes/cwc18/sambal-goreng-jawa-versi-simple.jpeg',
    'https://youtu.be/jHwU4x9dSgw?si=x3tiYL4s6ZyrDyJq',
    1821,
    '/images/recipes/cwc18/sambal-goreng-jawa-versi-simple.jpeg',
    1821
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    time = EXCLUDED.time,
    author = EXCLUDED.author,
    volume = EXCLUDED.volume,
    base_servings = EXCLUDED.base_servings,
    rating = EXCLUDED.rating,
    status = EXCLUDED.status,
    is_featured = EXCLUDED.is_featured,
    ingredients = EXCLUDED.ingredients,
    steps = EXCLUDED.steps,
    notes = EXCLUDED.notes,
    tags = EXCLUDED.tags,
    image = EXCLUDED.image,
    video = EXCLUDED.video,
    cover_image_id = EXCLUDED.cover_image_id,
    hero_image = EXCLUDED.hero_image,
    hero_image_id = EXCLUDED.hero_image_id;

COMMIT;
